### ISSUE TITLE
Unable to register on forum

### ISSUE THREAD

**Issue by golaat** [EventGhost/EventGhost#10]
I have tried to register on the eventghost [forums](http://www.eventghost.org/forum/) under three separate user names with three separate e-mail hosts and have never gotten the confirmation e-mail.  I have attempted to resend the notification multiple times to each, yet nothing ever arrives.  There is no contact information on the [eventghost.org](http://www.eventghost.org) site.

**Comment by topic2k** [comment]
I've send a PM to the site admin with a link to this issue. Let's see if he can do something.
Meanwhile i try to register another account to confirm the issue.

**Comment by blackwind** [comment]
Fixed according to the admin.
