### ISSUE TITLE
Traceback on exporting plugins

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#100]
I get the following Traceback when I try to export a plugin:
```
Traceback (most recent call last) (0.5.0-beta3):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\AddPluginDialog.py", line 154, in OnCmdExport
    eg.PluginInstall.Export(info)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\PluginInstall.py", line 108, in Export
    title = eg.text.MainFrame.Menu.Export.translate(None, "&.")
TypeError: translate() takes exactly one argument (2 given)
```
My EventGhost is set to German, I don't get any error if I set it to English

**Comment by topic2k** [comment]
Replacing `translate(None, "&.")` with `.replace("&", "")` eliminates the error. This line is just to remove the '&' from the menu label to use it as a title for the file dialog.

**Comment by blackwind** [comment]
A method that takes a different number of arguments for unicode strings? Go figure.

As @topic2k notes, an incredibly easy fix. I'll get it merged right away.
