### ISSUE TITLE
Resizing window cuts off the text at the bottom of the log

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#107]
I know that previous versions of EventGhost worked in this manner. It would always have the last line of the log fully visible and have the top line be chopped off if the log was full and the size of the frame didn't allow for a perfect set of lines to fill the log.

Now if I want to do something as simple as just make the frame smaller. I have to tinker with it to make sure i get that bottom line completely visible.

**Comment by blackwind** [comment]
As I noted in #97, this is a wxWidgets problem. If you want them to follow the correct Windows way of doing things, you'll have to file an issue with them.

**Comment by kdschlosser** [comment]
if this is a wx widgets problem how come it wasn't in previous versions of eg? is it something that is specific to this version of wx?

**Comment by blackwind** [comment]
It would seem so. If you take a look at the [list of changed files](https://github.com/EventGhost/EventGhost/pull/35/files) in #35, `eg/Classes/MainFrame/LogCtrl.py` isn't among them, so it wasn't anything @topic2k did.
