### ISSUE TITLE
"Log Debug Info" doesn't create file

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#108]
There is a bug in the Log Debug Information. when selected 2 things take place.
#1 it is not a real time change. you have to restart EG.
#2 the way the debug used to be handled was from a cli, and the eg.debugLevel was set from the cli arguement. and so when the eg.log was created it would set the stderr and stdout according to that.

problem with this is. 

#1 because the creation of the std overides is done at startup and there are 2 seperate sets of classes one for the debug and one for normal. this does not change unless a restart of eg takes place. hence the reason the realtime does not function.

#2 basically the same as the above but because the file writing bits are stored in the debug set of classes and the log is created before the menu items load and the eg.debugLevel gets set by the menu item .  the stdout and stderr has already been set to a non logging state.

this is a simple fix by simply adding this to the end of the stdout.write

    if eg.debugLevel:
        try:
            oldStdOut.write(data)
        except:
            oldStdOut.write(data.decode('mbcs'))

from the debug stdout and putting it into the normal one

and changing the stderr.write to this

    if eg.debugLevel:
        oldStdErr.write(data.decode("mbcs"))
    else:
        log.Write(data, ERROR_ICON)

and deleting the debug versions of the stdout and stderr classes along with the checking for the debugging

this solves both problems in one swat

**Comment by blackwind** [comment]
I'm not seeing what you're seeing and I have no idea what "file" you're referring to, but I agree that the code isn't correct, so I've fixed it in 3fc6a1a.

**Comment by kdschlosser** [comment]
log.txt file that was always created when running EG with the -debug CLI arg
located in  %APPDATA%\Roaming\EventGhost

it doesn't make the file

**Comment by blackwind** [comment]
Confirmed. I've recommitted the fix, and it appears to work now.
