### ISSUE TITLE
Migrate from `VistaVolEvents` to `AudioEndpointControl`

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#109]
Now that the wheels are in motion, I'm opening an issue to track and discuss this important addition. Thanks for taking it on, @ThomasBott and @jonisb!

**Comment by jonisb** [comment]
So I looked at what the `VistaVolEvents` is used for in EventGhost 0.4

There are 6 actions that use it:
**"MuteOn", "MuteOff", "ToggleMute" and "GetMute":**
    All the *Mute* actions use vistaVolumeDll.SetMute() and/or vistaVolumeDll.GetMute()
    All but Toggle is available in AudioEndpointControl but that's simple to implement.

**"SetMasterVolume" and "ChangeMasterVolumeBy":**
  Set/Change-MasterVolume uses vistaVolumeDll.GetMasterVolume() and vistaVolumeDll.SetMasterVolume().
  Is supported by AudioEndpointControl so should be no problem.

Also 2 event-handlers are registered:
**"RegisterVolumeHandler(self.VolumeEvent)" and "RegisterMuteHandler(self.MuteEvent)":**
Looks like the AudioEndpointControl supports detection of "Volume" events but not "Mute" events.

AudioEndpointControl supports getting and setting more options like changing volume on different audio channels, so EventGhosts support could be expanded, and I think the backward compatibility could be maintained.

**Comment by ThomasBott** [comment]
That sounds good! What are we going to do about the Mute event? I hope we'll not have to do polling...

I'm sorry for not being able to tackle this topic yet, I didn't find time last weekend to work on this topic and I have to work next weekend for my company, so probably the weekend after I'll find some time for it.

@blackwind : You set new feature milestones for 0.5 after releasing the beta? Don't get me wrong, I like all of them, the sooner they are implemented the better, but maybe we want to call it 0.5.1 then, what do you think?

**Comment by jonisb** [comment]
Everything that VistaVolEvents did is supported by my [AudioEndpointControl](https://github.com/jonisb/AudioEndpointControl) lib now, I might change some stuff before I feel it's ready for primetime.

**Comment by blackwind** [comment]
Tentatively tracking a few things for v0.5 for now since this is probably going to be a long, long beta. Gotta wait for a critical mass of plugins to be updated. If you don't finish until release candidate time (or close to it), I'll bump the milestone as needed.

**Comment by ThomasBott** [comment]
Ready for testing / integration:
http://www.eventghost.net/forum/viewtopic.php?f=10&t=8067&start=15
