### ISSUE TITLE
Future of this repository?

### ISSUE THREAD

**Issue by topic2k** [EventGhost/EventGhost#113]
Hello @blackwind, what are your intentions with this repository? Would you give me admin rights? It would be a pity if we loose all the issues and PR's.

At least it would be nice to have a feed back that the messages have reached you. TIA

**Comment by dequi** [comment]
@CarsonF, I agree with topic2k. It is not beneficial to the project to have this repository get stale and die, while different forked projects arise. Please consider granting at least topic2k admin rights, or let your reservations and intentions be known. Thanks.

**Comment by topic2k** [comment]
And a minute later the invitation was canceled. ❔😕

**Comment by CarsonF** [comment]
Hmm I may have derped
