### ISSUE TITLE
Updating Internationalism 

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#123]
I have started working on updating Internationalism in EG. What I have started to design is a real time translation in conjunction with the already built in language support. what this will do is build a translated word dictionary as EG is being used. and it will save that dictionary when eg is closed in order to minimize the polling of the translation server. Because of the nature of this type of system it does have a performance hit on EG when a word is not found in the local dictionary but as time goes on and EG gets used that performance hit will go away. 

This system will translate events as well not just the UI text

**Comment by jonisb** [comment]
Interesting, but I'm wondering how useful a "word" based translation  would be.
Words can be translated but could mean totally different things in different situations.

I haven't looked into how EventGhost does the language stuff as I use the default english,

What translation server are you going to use? As I need it for a another project that I was going to use the Google one for, but that was changed to a pay service, and that's not practical for a simple free software.

**Comment by topic2k** [comment]
> This system will translate events as well not just the UI text
If you translate the events, do you just do it in the UI or even in the xml/egtree file? I'm sure you won't, but wanted to ask, just in case.  ;)

**Comment by jonisb** [comment]
> This system will translate events as well not just the UI text

I'm not sure I like this, will make support impossible for plugins, (user posts log message/screenshot) unfortunately it's in a different language, so you have no clue. Especially if badly auto translated. 

So an example of a bad translation (I assume not auto-translated), I have a software installed "Killer network manager", unfortunately it uses Swedish (No option to change) as its UI language, so to exit the program there is a menu "exit" problem is it's translated to "utgång" which is a direct translation, but I have never seen it used to exit a program, you would use "avsluta", "stäng" or "stänga av".

jonib
Bad translations is a big part in why I use English is available.

**Comment by kdschlosser** [comment]
this is one of those things that the user can select... but also... now you are going to love me for this one... you don't have to restart EG

so support issues go away because you can simply instruct the user to change to English then do the screen shot.

and no the xml stays as is.

how this works is.. when you start up EG for the first time... it will build a language file for all of the 80 something languages that are supported. with one entry that has been translated and that's for the name of the language it's self..

kind of pointless to show a list of language names to choose from and they are all in english and you don't read a lick of English. I know the flags are there to help. but.... i have EG now pulling the proper set language from windows.

the software automatically pull the "correct" language set from windows and not how it is done right not by pulling the language from locale

current eg method
locale.GetLanguageCanonicalName(locale.GetSystemLanguage())

the issue with this is the language specified in your locale is not the same as the language used to display the text in the UI. these can be 2 different things

by using ctypes to get a number representation of what the language the UI is displaying you are able to use that number to cross reference it against locale's list of string language codes to get the string version like this  'en_US' 

locale.windows_locale[ctypes.windll.kernel32.GetUserDefaultUILanguage()]

so now that w are getting the displayed language we can have EG automatically start up in that language and it will be correct. and we know the person using the computer reads that language because that is what windows is displaying currently..

so there wouldn't be an issue of having a local in germany and the person is new to germany so has the UI text set to english. the current way would open EG in german... so they have to play the guessing game to try and find the menu with the flags...

come on now... that's NUTZ

but this works the correct way
so that fixes one issue.

the other is the use of the current files. if someone has spent the time to Translate then you will have only a partial word list, because all of the plugins would have to be done as well.. and with the current manner in which it is done. if you have 2 plugins that use the same work. you have to have it in there 2 times.. BLAH!!

this is also set up just for you jonib you have the ability to change words in the event the translation is wrong... because it will only go and get the word one time and then stores the translation in a language file. that gets saved at the close of each EG session. this takes care of excessive retrieval from the internet..
which we know you loose internet every now and again jonib ;) man oh man. i am trying to cover all of the bases here

but it works. i have it all done for the UI menus and the eg.translatableStrings just have to go through the rest of it for the events. and any other random bits that happen about..

Now eg does take a bit to load the first time you start it up. because of it's need to go and translate every single piece of text. i am working on trimming that time down now. before i had to getting each word individually so now i am working on sending a list of words. namely a whole eg.translateableStrings subclass in one wack. because the server i am using (which i think is the only free one available) isn't the fastest thing at the connection end of things. better to send in one big clump then a bunch of smaller ones and the use of requests or urllib2 is minimized thus speeding up things as well.. but again this is only slow for the first time EG is run after that it has a working language file to use from. and the single things that may pop up here and there don't impact speed that much. but with the loading of a new plugin is what i am concerned about and i don't want it to take 5-10 seconds for the thing to load..

the nicest thing about this is... if by chance someone wanted to code a plugin for EG and have a subclass of eg.translateableStrings full of russian. it will convert it to any language automatically detecting the incoming language and translating it to whatever is set in EG.

any thoughts?? anything i may be missing??

**Comment by kdschlosser** [comment]
and as far as the "phrase" lookup goes. i will make it so that the phrase will be looked for first and if not found then to convert based on words. and with the ability to change/add to the language file the person could then add the phrase and the translation of the phrase so it would use that first

**Comment by jonisb** [comment]
> so support issues go away because you can simply instruct the user to change to English then do the screen shot.

I guess that concern is dealt with, looking forward to see it in action.

> the software automatically pull the "correct" language set from windows and not how it is done right not by pulling the language from locale

This sounds perfect, many software companies like nVidia uses my location and not my UI language, which is impressive how they can't get something like that right. (and they might even not allow the user to change it like nVidia)

> this is also set up just for you jonib you have the ability to change words in the event the translation is wrong... because it will only go and get the word one time and then stores the translation in a language file. that gets saved at the close of each EG session. this takes care of excessive retrieval from the internet..

Will this be just a local thing or will the improvements get back to EventGhost?

> any thoughts?? anything i may be missing??

Not for the moment. ;)

jonib

**Comment by kdschlosser** [comment]
the alterations would be a local thing because it builds the language file real time. this also keeps the foot print on the small side as not to have it populated with words that a user may not need

**Comment by kdschlosser** [comment]
well jonib. maybe you can tell me if i am wasting my time or not


here is a sample of the language file...

you can tell me how accurate it is

`u"Plugin load error!": u"Plugin belastning fel!",
    u"Plugin start error!": u"Plugin startar fel!",
    u"Popup Menu: Background Color": u"Popup-Menyn: Bakgrundsfärg",
    u"Popup Menu: Text Color": u"Popup-Menyn: Sms: A Färg",
    u"Preview Minimized Panes:": u"Förhandsgranska Minimerat Fönster:",
    u"Red": u"Röd",
    u'Refresh environment before executing "Run" actions': u'Uppdatera miljö innan du kör "Run" - åtgärder',
    u"Resize window proportionally": u"Ändra storlek proportionellt",
    u"Sash Color": u"Skärp Färg",
    u"Sash Settings": u"Skärp Inställningar",`

**Comment by jonisb** [comment]
> well jonib. maybe you can tell me if i am wasting my time or not

Well not up to me as I wouldn't use it anyway, so someone like Pako would need to tell us if bad translation is better than the original language.

> u"Plugin load error!": u"Plugin belastning fel!",

Becomes "Plugin strain error" Not quite right.

> u"Plugin start error!": u"Plugin startar fel!",

Becomes "Plugin starting error".

> u"Popup Menu: Background Color": u"Popup-Menyn: Bakgrundsfärg",

Correct.

> u"Popup Menu: Text Color": u"Popup-Menyn: Sms: A Färg",

Becomes "Popup Menu: SMS: A Color" Not quite right. 

> u"Preview Minimized Panes:": u"Förhandsgranska Minimerat Fönster:",

Becomes "Preview Minimized Window:" Almost.

> u"Red": u"Röd",

Correct

> u'Refresh environment before executing "Run" actions': u'Uppdatera miljö innan du kör "Run" - åtgärder',

"Action" becomes "measure" which isn't wrong but does look a bit off.

> u"Resize window proportionally": u"Ändra storlek proportionellt",

Correct.

> u"Sash Color": u"Skärp Färg",

Becomes "Belt color" Where is this from don't seem computer related (Something with ribbon?)

> u"Sash Settings": u"Skärp Inställningar",

Becomes "Belt Settings"

jonib

**Comment by ThomasBott** [comment]
OK, let me give you my 2ct on this: I'm currently using EG in my local language (German) and it's fine for me, some actions and descriptions are translated, some are not and displayed in English. But the bit of German that is there is correct, so it's a little improvement for me. Now, if there was some or even a lot of wrong translation I'd directly turn off translation. I hate it if something is translated incorrectly.
I'm working in an IT department and I often need to go to microsoft.com for some KB article and they use  automated translation - it's totally useless, I don't understand anything until I switch it to English.
Also in Windows, Microsoft had the great idea "hey, let's translate the command line tools as well!" Great idea, makes scripting a nightmare in an international environment -> separate script for each language, fun, especially if you can't talk 15 languages - oh and don't let me start about the event log troubleshooting (yes, they translate the events, without an option to switch the language ;-) )
So, when I read something like "translate events" I see red!
@kdschlosser I'm sure your approach is better than the one from Microsoft, but still I question if a automated translation makes sense.
I personally prefer no translation over bad translation. I think I'd just switch to English when you integrate it, which would be a shame as you put quite some effort into getting this to work properly...

Again, just my personal opinion, others may think different.

PS.: "English" means "native" right? It won't translate an event with some German in it to English, would it?

**Comment by kdschlosser** [comment]
this is why i am testing and wanting to know how  the translations are..
and these were done as phrase translations. not word by word.

and i am also running into a real bear with string formatting there are a lot of plugins that use the %d %s and {variable} and store this strings in an eg.translateableString subclass..

and my issue is not with removing the formatting to get the translation. it's getting it back into the same place also. for example with Chinese a single "character" can be a whole sentence LOL or at the very least a couple of words. so the number of characters change and having it put back into the right place is an issue.. now I could just bypass and not do a translation on those as there really aren't that many of them on a per seat basis. maybe 10 at the most for a normal installation. and the use can go and translate them.
it is kinda cool seeing the UI in a completely different language tho.

PS.: "English" means "native" right? It won't translate an event with some German in it to English, would it?

sure would. if you have the language set to en_US then it would translate anything that is not English to English. there would be options to turn on or off specific pieces of it. and you would have the ability to edit the language file... because it only does a translation once for a specific phrase or word and then stores it and when EG gets closed it writes the file. so setting up a dialog to manually do the translations it will not go and overwrite it.

and I know automatic translation is hit or miss... but if it gets says about 50% correct, that's 50% less that has to be manually done... that is kind of the way i see it...

and nothing is not without user interaction. you  would have the ability to set whatever language you want...
and you would have the ability to turn off translation for things like the events. the big issue with how it is done now is there is no way for the plugin developer to add a translation file to a plugin. it has to be done by the user and with the language editor.. I personally think this is a kind of odd way to go about it.. 

I was really curious to see how accurate it is and if it can be done in an efficient manner. and it does work. and it pretty quick about it.. and i got the after install load time down. 

I know there are also a world of other issues as well because what happens is the actual eg.translateableStrings subclass gets replaced with a duplicate that has all the attributes translated. now if for some reason the plugin dev doing a string comparison in code against one of the attributes in the "Text Class" it's going to fail. because there is no mechanism to deal with that sort of thing...

I know it was a good effort on my part. but I do also know it will never work properly and will be to much of a pain to code around... 

BUT i do see a need for adding the ability for a plugin dev to add translation files to his/her plugin instead of the user having to do it... and also fixing EG pulling the language from the wrong place. I have the code for that and i will issue a pull request for it... I am going to have to set up another eg fork so the copies are identical or i can simply paste the code in here and it can get added. it's only a few lines..

so what do you all think about the plugin language files?? and should it just be files set up just like EG but in a folder called languages and then use the language code as the file name and have a duplicate class as the core one used.??? i fell that would be the easiest to look for and the mechanics of reading the file are already in place so we would just have to separate the core plugins out so they all follow the same protocol.. and it would still be editable. but moving that editor dialog into EG instead of a command line trigger and also having it reload the UI on a language change is really no biggie because all you would have to do is hide the ui. which destroys it. and then show it and it gets rebuilt so the data should be there. and as far as the plugins. forcing a refresh on them is no biggie either

**Comment by jonisb** [comment]
> sure would. if you have the language set to en_US then it would translate anything that is not English to English. there would be options to turn on or off specific pieces of it. and you would have the ability to edit the language file... 

Hopefully I misunderstood this, but if I choose English as my UI language but then use some Swedish somewhere I would not want that translated to English. There need to be an option to turn off any auto translation.

jonib

**Comment by kdschlosser** [comment]
I am thinking about using the auto translation for just events due to the one word nature of them the trnslations should be pretty accurate. and it can be turned on and off but as far as translations for plugins there needs to be a means for the plugin dev to supply them.
and the UI should come with a full set

**Comment by per1234** [comment]
I think being able to include translations with a plugin would be a really useful feature and even more so when the plugin manager is added and most or all of the plugins are no longer bundled with the application since that means the translator will only be translating the plugins they happen to have installed. I think it would be best if it used the standard translation editor system but saving each plugin's translations to their folders as separate files. Likely the plugin author won't usually be doing the translations so it's important to make it easy for people to contribute translations to plugins.

**Comment by kdschlosser** [comment]
that's why i stated to use the mechanism that EG is already using just separate the plugins form the core. we just have to make plugin authors aware that the "Text" class is specifically for the intention of translating text, and the attributes that are set in it are not to be used in an opperations other then being displayed on the screen...

now if there is no "automatic" translation" of the text and it has to be done manually then the use of string formatters such as %s %d and {format} can be used with no problems. now upon reading the code for EG it appears as tho a dictionary does not get translated at all.. but i could be mistaken in how it's handled.

but the big thing to this and the reason why i do not believe there are any translations being done  now is that the having to launch the editor from a CLI and that information is not POW right in your face and would require you to do some document reading or forum searching..

it needs to be right there in a menu. probably a button located in the same place where you set the language. and to be honest there should be a drop down called settings and in there would be where you put another dropdown for selecting a language as well as a menu option for editing them.

i do not feel the use of a dialog to house all the various settings is needed. it should be a dropdown and if there is a vast many options for a specific setting like setting the UI colors for instance then have a dialog for a setting. i have compiled a whole list of language names that are translated to the language of that name... i think that should be used in a list of language selections instead of all English language names.. which i think would display nice as a sub menu of a setting menu.

to make this a really easy thing to do for plugins it should be that if there is a languages folder in the plugin folder the files in that folder would be en.US.py for english, ru_RU.py for russian. and so on and so forth. and that is where the Text class would be housed. not in the __init__.py the plugin dev will just have to do an import. i say this because if a plugin is not written in english then the plugin dev could import whatever Text class he is dealing with and if he/she has a translation file to english then it will be "translated" i feel this is a far better way as not to force plugins to be written in english

**Comment by ThomasBott** [comment]
I thought about the auto translation last night and I really see little to no benefit. The only people this would by a help for, are the ones that don't know any English and that's not the target group of EventGhost I think.
People like me would just turn this feature off (if possible), as they are just pissed off by wrong/misleading translations. Especially for events!
I do very much welcome the idea of having separated language files for plugins though! I think this would improve things a lot! As per1234 mentioned, there should be an easy possibility to edit those from the UI (if possible). The plugin developper most likely can't speak all languages, so other people can help with translating (properly ;-) ) and share their translation files with others or make a commit for them on the plugin.

**Comment by kdschlosser** [comment]
sweet. that is now 3 that are thinking this is the way to go. I am trying to crunch how to handle this is a manner that will not cause an issue with a plugin. because of the use of text comparison. EG as of now replaces the eg.translateableStrings with a translated version if a translated version exists... the isse wuth this is if you plugin makes a call like this..

def __call__(self, attrName):
    attr = getattr(self.text, attrName)
    if attr == 'this is a test string':
        do some code

it will always return false if a language has been made for that plugin...

this is for use as an example. and i do not know how often someone would do something like this...

i do not know if you can try: except: a return and have it catch an exception for it. then return the non translated version instead
