### ISSUE TITLE
"Build CHM docs" not fully working

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#13]
As previously discussed, the "Build CHM docs" build step still needs some work:

* CSS doesn't appear to be added.
* Version is listed as "vdeveloper" in some areas, but not others.
* What else?

We need to resolve this before closing #2.

**Comment by topic2k** [comment]
You probably have a newer sphinx version (like i had). I installed sphinx 1.0.7 and then .chm-file is build correctly.

**Comment by blackwind** [comment]
For future visitors who might be trying to put together a build environment, I just want to point out that you can now use the latest version of `sphinx` again after the above pull request.
