### ISSUE TITLE
Appveyor Fails - "more then one solution file exists..."

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#131]
When I added a pull request appveyor failed with the message "more then one solution file exists..."

Then it changed to stating it passed. and there is no log entry of the failure.
I do not know if this could cause an issue somehow. or if it's a "That's just how it works" kinda thing

**Comment by kdschlosser** [comment]
Here is a screen shot of the failure

![appveyor fail](https://cloud.githubusercontent.com/assets/10932297/21191593/e12cc716-c1e2-11e6-9759-f62e5fcd959e.png)

**Comment by per1234** [comment]
The same just happened with https://github.com/EventGhost/EventGhost/pull/135 and, as with yours, it now shows a successful build. I had just submitted a different PR several minutes before that happened so I wonder if it's related in some way to that? I see that the timestamps on your 130 and 132 builds were <1.5hrs apart.

**Comment by kdschlosser** [comment]
I do not think it has anything to do with the space between pull requests. it has done it for every one of them. i just managed to get a screen shot. and i thought i was going a little batty when it first did it. and then when it showed that it passed. i wasn't sure if i was mistaken. but then i saw it again and then on the 3rd time i finally posted the bug report. and the screen shot.

**Comment by topic2k** [comment]
I think that's my "fault". I added another webhook for appveyor, because i don't have access to the one created by blackwnd.
