### ISSUE TITLE
Restoring EventGhost from tray results in an empty Log

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#138]
In EG 0.5 beta5, Restoring EventGhost from tray results in an empty Log, the log can still be filled by new events and actions but the ones happened while EG was hidden (or before) are gone.

**Comment by kdschlosser** [comment]
This also happens in beta4

**Comment by ThomasBott** [comment]
worked in beta 4 for me...

**Comment by kdschlosser** [comment]
HUH that's odd. I will have to recheck and make sure i don't have my eg versions crossed somehow.

**Comment by ThomasBott** [comment]
Problem has been caused by #124

**Comment by topic2k** [comment]
Nope 😉  the cause is the change in LogCtrl.py in #118

**Comment by ThomasBott** [comment]
oh, possible. I just took the file after #124 but didn't check if there was another commit to it before (after beta 4)
Sorry :-)

**Comment by topic2k** [comment]
No problem. Saying it was related to #124 pointed me to the right direction.  :-D
