### ISSUE TITLE
EventGhost doesn't minimize to the task bar

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#139]
EG 0.5 beta5
if ´Display EventGhost icon in system tray´ is disabled, EventGhost doesn't minimize to the task bar (if I'm not mistaking, it did this in version 0.4) I think all 0.5 versions are affected.
You can only bring back the UI by executing the EG .exe

**Comment by kdschlosser** [comment]
I confirmed this behavior in beta 4

**Comment by ThomasBott** [comment]
Replacing the function OnIconize in eg\Classes\MainFrame\__init__.py with this one:

    def OnIconize(self, event):
        """
        Handle wx.EVT_ICONIZE
        """
        # On iconizing, we actually destroy the frame completely
        if eg.config.showTrayIcon:
            self.document.HideFrame()
        else:
            event.Skip()

And function OnClose in eg\Classes\MainFrame\__init__.py with this one:

    def OnClose(self, dummyEvent):
        """
        Handle wx.EVT_CLOSE
        """
        if len(self.openDialogs) == 0:
            if eg.config.hideOnClose:
                if eg.config.showTrayIcon:
                    self.document.HideFrame()
                else:
                    self.Iconize()
            else:
                eg.app.Exit()
        else:
            self.RequestUserAttention()

Resolves this issue, credit goes to @kdschlosser

**Comment by topic2k** [comment]
Confirmed. Please do you or @kdschlosser a pull request.

**Comment by topic2k** [comment]
fixed in #145
