### ISSUE TITLE
Speech plugin issues

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#148]
I've found a few issues with using the Speech plugin with the beta releases:

- Errors when adding a "Text to speech" action caused by strings from the Text class in TextToSpeech action. ~~I've fixed this issue as shown here: https://github.com/EventGhost/EventGhost/pull/156/commits/a70a8ba19f84a3ae368791626db78934ca921391.~~
EDIT: A better fix has been proposed by topic2k: https://github.com/topic2k/EventGhost/commit/856ad1ac1ce6d5fee596acff2f157339802da186 but has not yet been merged.

- ~~wxGridSizer error when adding a "Text to speech" action. I've fixed this issue as shown here: https://github.com/EventGhost/EventGhost/pull/155/commits/9690d6aeae5570699f7e57164828ae096ee4a216~~ EDIT: Fixed by the merge of https://github.com/EventGhost/EventGhost/pull/155

- ~~"Member not found" error when executing the "Text to speech" action:~~
```
16:57:14   Exception in thread Thread-5:
16:57:14   Traceback (most recent call last):
16:57:14     File "threading.pyc", line 801, in __bootstrap_inner
16:57:14     File "C:\Program Files (x86)\EventGhost\plugins\Speech\__init__.py", line 216, in run
16:57:14       tts.Voice = voices[ix][1]
16:57:14     File "win32com\client\dynamic.pyc", line 565, in __setattr__
16:57:14   com_error: (-2147352573, 'Member not found.', None, None)
16:57:14   
```
~~The same issue occurs with Windows 7 64 and 32 bit with all EventGhost beta releases and the build of the current source. The error doesn't occur with the current stock Speech plugin or my modified version of the plugin with EventGhost 0.4.1.r1722.~~ EDIT: fixed by the downgrade of pywin32 to 2.19, thanks topic2k!

EDIT: I only have the stock "Microsoft Anna" voice installed.

**Comment by topic2k** [comment]
Please do pull request for the first two issues.
The third issue seems to  a problem with the used pywin32 version. Version 2.20 raises the exception, version 2.19 works. For the next build i will use pypiwin32 version 2.19.

**Comment by per1234** [comment]
Closed by https://github.com/EventGhost/EventGhost/pull/179
