### ISSUE TITLE
Generate changelog from pull requests instead of commits

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#15]
@topic2k's build script update (#8) contains the ability to generate a changelog from Git commits. I suggested we only include the title/subject of each commit rather than the full body, but I fear this will still produce far too much noise for the end-user.

Consider the following recent commit messages:

* "Added README with project description and slack link"
* "Restored manifest file."
* "Merge pull request #8 from topic2k/develop"
* "Add .gitignore"

Do we really want all that in the changelog? Does the user care about any of these things?

Here's what I'm thinking we should include, ordered by order in the changelog:

* Merged pull requests with the `notice` tag ("Important changes for plugin developers:")
* Merged pull requests with the `enhancement` tag ("Features added:")
    * Except where also tagged with `internal`
* Merged pull requests with the `bug` tag ("Bugs fixed:")
    * Except where also tagged with `internal`

There's a Ruby project called [GitHub Changelog Generator](https://github.com/skywinder/github-changelog-generator) capable of producing this result. I don't think we should use that project directly to generate our changelog, as the last thing we need is a dependency on another language, but I think we should aim to reproduce [its excellent Markdown output format](https://github.com/skywinder/Github-Changelog-Generator/blob/master/CHANGELOG.md).

Added bonuses:

* If this completely eliminates the need for `pygit2` (and, by extension, libgit2), the process of setting up a build environment will be greatly simplified.
* We can publish the Markdown output to our GitHub releases (#14).

We need to resolve this before closing #2.

**Comment by blackwind** [comment]
I've been thinking about the content of the above post, and I've identified a potential stumbling point -- we can compare the date an issue was closed with the date of the last release, but does that tell us the whole story?

Consider the following scenario: We release v0.5.0, then we begin work on v1.0.0. For v1.0.0, hypothetically, we upgrade to Python 3. We've converted the source tree to Python 3, but we're not ready to release it, and suddenly the need arises to put out a patch release, v0.5.1. We checkout the `v0.5.0` tag, commit our bugfix, begin building the v0.5.1 release, and the changelog generator picks up and adds the closed "Upgrade to Python 3" issue. Not good.

I don't think there's any way to reliably generate a changelog from issues. Pull requests, though? Not only can that still work, it's probably what I should've suggested in the first place, as every closed issue listed would've had a duplicate in the list of merged pull requests.

Currently, the changelog is being built by traversing the commit history and writing out each individual commit subject. If we continue traversing the commit history, but instead look for commits starting with "Merge pull request #", we can always reliably tell what is and isn't in our new release.

From there, we can look at automatically generating version numbers as well so there's never any confusion as to what we should brand our new release:

* We create two more issue labels tentatively titled `major++` and `minor++`.
* We keep `VersionRevision.py` inside the tree when it's generated instead of writing to a temporary folder.
* We add a `beta` value to `VersionRevision.py`.
* We change line 22 in `Version.py` to `base = string = "{0}.{1}.{2}".format(major, minor, patch) + ("-beta" + beta if beta else "")`.
* When building, we save the original value of `beta`, then:
    * If the pre-release checkbox you suggested in #25 is checked, we increment `beta` by 1.
    * If the pre-release checkbox isn't checked, we reset `beta` to 0.
* If the value of `beta` was originally 0, when the changelog is being built:
    * If it finds any merged pull requests labelled `major++`, it increments the major version from `VersionRevision.py` by 1 and resets minor version and patch version to 0. Multiple `major++` labels in the same release shouldn't increment the major version multiple times.
    * If it finds any merged pull requests labelled `minor++`, it increments the minor version from `VersionRevision.py` by 1 and resets patch version to 0. Multiple `minor++` labels in the same release shouldn't increment the minor version multiple times, and `minor++` should be ignored if any `major++` labels are found.
    * If no `major++` or `minor++` labels are found, patch version is incremented by 1.
* If the value of `beta` _wasn't_ originally 0, we don't increment major, minor, or patch (so we don't end up with things like v0.5.0-beta1, followed by v0.5.1-beta2 instead of v0.5.0-beta2 as expected).
* When we write and commit the changelog, we also write and commit `VersionRevision.py`.

This method will continue to work correctly even in the v0.5.1 scenario outlined above, as the `v0.5.0` tag will contain the v0.5.0 `VersionRevision.py`, and it won't contain the merged Python 3 pull request with the `major++` label.

**Comment by blackwind** [comment]
I've gone ahead and scratched out the version number stuff above. Let's concentrate on the original topic of the issue. When this, #51, and what I'm working on now are done, I'll release v0.5.0-beta1.

**Comment by blackwind** [comment]
Alright, I'm officially done making changes until after beta1. You can work on this without fear of merge conflicts, @topic2k. If there's anything else you're working on you'd like to land before beta1, let me know on Slack.

**Comment by blackwind** [comment]
> hello blackwind , regarding your comment https://github.com/EventGhost/EventGhost/issues/15#issuecomment-220885440 , i wasn't aware that you think i'm working on it. Well, i wasn't, but now i was inspired and tried to convert the changelog-generator to python. Look already promising: https://github.com/topic2k/EventGhost/blob/master/CHANGELOG.md but i haven't tested it much yet. And i know there are some issues.

Oh, you're converting the entire project? Isn't that overkill (unless there's something I'm missing)? The code is already in the build script to utilize `agithub` to download commits; from there, it's just a matter of looping through, finding the pull request merge commits, loading the associated pull requests with `agithub`, comparing the tags, and slotting each item into the correct location. Converting the entire project instead of just stealing the output format and adding it to our existing code means yet another dependency, and unless you plan on maintaining it long-term on PyPI or Chocolatey, it's a dependency the user will have to download and install themselves.

Either way, so far so good on the output. I see there are a number of changes missing and a number that are `internal` and shouldn't be listed, but it sounds like you're already aware and on the case.

**Comment by topic2k** [comment]
> Oh, you're converting the entire project? Isn't that overkill (unless there's something I'm missing)? 

If it were only for EG, then surely yes. :)  but it's another challenge i'd like to do and now i understand a bit of ruby. :D

> The code is already in the build script to utilize agithub to download commits; from there, it's just a matter of looping through, finding the pull request merge commits, loading the associated pull requests with agithub, comparing the tags, and slotting each item into the correct location. Converting the entire 

When i have some more time (by the end of July at least), i will look at making the changes.
