### ISSUE TITLE
Copied tree items are not given a unique XML_Guid value

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#159]
EventGhost version: build at 74baa28561cbe4712c4f01804800d6ccee315456 and 0.5.0-beta5.
OS: Windows 7 64 bit

https://github.com/EventGhost/EventGhost/pull/133 is intended to add "a unique GUID to each treeItem" as the `XML_Guid` property. If a tree item is copied and pasted then it has the same `XML_Guid` value as the item it was copied from.

Steps to reproduce:
1. Right click on any tree item.
2. Click "Copy".
3. Right Click on the tree.
4. Click "Paste".
5. File > Save.
6. Open the saved file in a text editor and examine the `XML_Guid` values.

Example:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<EventGhost Version="WIP" Guid="{6F4B8AA4-2AA2-4128-9602-1CD742DF9EC1}" Time="1483836574.19">
    <Autostart Name="Autostart" XML_Guid="{9D8D1667-0F95-453A-AA83-8D8191252A3C}" />
    <Macro Name="Comment" XML_Guid="{CC9372C6-2EBB-4A29-9593-ED7341810B76}" Expanded="True">
        <Action XML_Guid="{C8F261CE-6B3B-4209-8D14-3EFB7164F67E}">
            EventGhost.Comment()
        </Action>
    </Macro>
    <Macro Name="Comment" XML_Guid="{CC9372C6-2EBB-4A29-9593-ED7341810B76}" Expanded="True">
        <Action XML_Guid="{C8F261CE-6B3B-4209-8D14-3EFB7164F67E}">
            EventGhost.Comment()
        </Action>
    </Macro>
</EventGhost>
```
CC: @kdschlosser

**Comment by kdschlosser** [comment]
Ahhh... I never thought about something copied. It's an easy fix. Will do it up when I get home.
