### ISSUE TITLE
Appveyor tries to launch the EventGhost -install -quiet to early

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#162]
There seems to be an issue with appveyor. it's not waiting until the build process is done before trying to run EventGhost.. and this causes appveyor to hang for an hour.

**Comment by topic2k** [comment]
I didn't change anything regarding appveyor. Don't know what's going on. Maybe an issue on the appveyor side?

**Comment by kdschlosser** [comment]
it failed for you also. and it did the exact same thing at the exact same spot.

as seen here in your latest ca422028 it failed. I was thinking that the user prompt was coming up on me. and that is one of the reasons why i have so many commits on #140 well Not all but I was trying to fix the fact it was hanging on appveyor. thinking it was because of the code. 

But can we add some kind of a flag that lets us know that appveyor is building.. and running EG. the reason why I ask for this is because I set up a prompt to inform the user if there is no config file and if they would like to make a new one. now on first time use and EG has never been installed this will always come up.. and it does it right away.. I do not think appveyor will answer the dialog. LOL and it will cause it to hang and then fail. if there was a way to know that appveyor was running it can be set to not ask the question.

the -install parameter doesn't actually start EG and I have it set right now to not ask if that parameter is passed. and also if isMain is not set it won't ask either. but I do not know what the whole appveyor test is about, so I do not know if it actually starts eventghost. I think it would be a good idea if it does and not just compile the files. but if it starts and then closes eg. this would be a better test. I mean you can even set the thing to load a specific tree and trigger a couple of events on start this will cause the macros to run and the macros can perform specific tasks to make sure everything is functioning properly..

**Comment by topic2k** [comment]
The appveyor test is still the one blackwind setup. A while ago i already made some tests with appveyor, but need some more research to do. I would like to replace the current setup, which is configured via blackwinds account, with a setup configured via a file. That way anyone can make changes to it through pull requests.

**Comment by kdschlosser** [comment]
that sounds like a plan

**Comment by kdschlosser** [comment]
I will start reading up on it as well and messing around with it. I want to learn about it also. and see how the thing works.

**Comment by kdschlosser** [comment]
awesome work on getting appveyor back up and running

**Comment by topic2k** [comment]
Thanks. Next step is to do a test run of EG (with -debug maybe) and eventually check for failures. (I hope to have a look at it at the weekend.)

**Comment by kdschlosser** [comment]
everything seems to be running proper now with appveyor, so i am going to close this
