### ISSUE TITLE
All recent AppVeyor builds show version as 0.5.0-beta6

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#193]
Up to and including [build 398](https://ci.appveyor.com/project/topic2k/eventghost/build/398-master/artifacts) the AppVeyor builds had versions based on the build date (e.g. build 398's version is `WIP-2017.01.31-16.30.01`). [Since build 398 all builds have the version `0.5.0-beta6`](https://ci.appveyor.com/project/topic2k/eventghost/build/408-master/artifacts). This is an issue because it's incorrect and makes it difficult to determine for sure which build is being used for beta testing. The AppVeyor build file names also have this issue.

**Comment by topic2k** [comment]
Uups, didn't notice that. Fixed it in https://github.com/EventGhost/EventGhost/commit/9cc2c411caf1fac09a8caef9fc96c97f1caae3cb
