### ISSUE TITLE
Windows 10 build 1607

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#194]
OK people this is a biggie... Microsoft has stuck it to us again.. 

we are going to have a major problem with any drivers that EG installs if you are running Microsoft's latest and greatest Windows. this is due to how they reworked the whole driver signing. it doesn't matter if you check that little box that says to install unsigned drivers.. it will not do it..

I have started to do some "light" reading on acquiring the proper certificates and accounts with Microsoft to obtain signed drivers. I have not come across anything that indicates a cost to this.. So if someone has experience with handling something like this then please chime in.

**Comment by topic2k** [comment]
As i read it, only [new installations of Windows 10, version 1607](https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/) are affected.

**Comment by kdschlosser** [comment]
yeah i know. that means every single OEM laptop and box that is produced is going to have this issue

**Comment by kdschlosser** [comment]
but you know Microsoft.. and i am not sure what this problem could be but there are 2 people using the same remote control that have the same install problem. and EventGhost goes to install drivers for it.. not sure if it's related. I am trying to work through it in the forum
