### ISSUE TITLE
Event log is scrolled to the top after restoring EventGhost from tray

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#198]
I have found a small issue: After EventGhost is restored from tray, the event log is always scrolled to the very top, which means you need to scroll manually to the bottom every time, to see the latest events.
EG 0.5 beta 6

**Comment by kdschlosser** [comment]
OK that should be pretty simple to fix. I will get it done in a few hours.

**Comment by kdschlosser** [comment]
or a couple of minutes
