### ISSUE TITLE
Plugin EGAppControl generates error in 0.5.RC2

### ISSUE THREAD

**Issue by gemboot** [EventGhost/EventGhost#223]
Hello,

I'm running Win10 Build 1703 with EG 0.5.RC2, I installed the plugin **[EGAppControl](http://www.eventghost.net/forum/viewtopic.php?f=9&t=3881)**, as soon as I start EG I get this error : 

> 08:53:39   ---> Welcome to EventGhost <---
**_08:53:40   Error reading help file C:\ProgramData\EventGhost\plugins\EGAppControl\LogMonitor.html, error=Invalid mode ('rtb')
08:53:40   Traceback (most recent call last) (0.5.0-rc2):
08:53:40     File "C:\ProgramData\EventGhost\plugins\EGAppControl\__init__.py", line 82, in GetFileAsStr
08:53:40       f = codecs.open(filepath, mode="rt", encoding="latin_1", buffering=-1)
08:53:40     File "codecs.pyc", line 896, in open
08:53:40   ValueError: Invalid mode ('rtb')_**
08:53:42   Autostart
08:53:42      Plugin: EG App Control
08:53:42   System.PowerSource.Line
08:53:42   Main.OnInit

I have to say that this plugin works perfectly with latest stable version of EG 0.4.1.r1722 with Win10 as well. So what could be generating this error ? The plugin needs to be adjusted ?

I thought I would share this "possible" bug.
Thanks

**Comment by topic2k** [comment]
This is a "bug" in the plugin, which is not part of the main EG installation. But the bug should be easy to fix: in line 82 remove the 't' in 'rt'.
Did you read the forum thread that you linked? It's already mentioned there: http://www.eventghost.net/forum/viewtopic.php?f=9&t=3881&start=30#p41329

**Comment by gemboot** [comment]
oh, I'm very sorry, of course I read the forum back then but I must admit not recently, I should have... sorry to have bothered you, next time I'll be more careful.

Thanks for the tip !
