### ISSUE TITLE
Virtual Mouse

### ISSUE THREAD

**Issue by bschley** [EventGhost/EventGhost#228]
It's possible to create a virtual mouse, without controlling the real mouse?

That I automatically control a program on my second monitor with EventGhost and working on my main monitor with the real mouse?

**Comment by kdschlosser** [comment]
hmmm.... good question

It can be done. but not with a mouse, and would be extremely complex. you would really need to know a lot of the inner workings of the GUI of the program you want to control

**Comment by bschley** [comment]
Do you have an example?

**Comment by kdschlosser** [comment]
it would all be in code. nothing simple.
