### ISSUE TITLE
Error on egplugin import if EventGhost is not running 

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#230]
23:37:16: 0 MainThread: PluginManager.ScanAllPlugins :2.3078852568378916
23:37:16: 0 MainThread: SendKeysParser.__init__()
23:37:16: 0 MainThread: PluginInstall.Import(filepath=u'c:\\users\\semicolon\\desktop\\audioendpoint.egplugin')
23:37:18: 0 MainThread: PluginOverviewDialog.Destroy()
23:37:18: 0 MainThread: PluginInstall.Import => None

EG 0.5 RC 2

**Comment by kdschlosser** [comment]
where is the error?

**Comment by ThomasBott** [comment]
I've only got the message that an Error occurred and if I like to view the log for details, that's what's in the log

**Comment by ThomasBott** [comment]
Wait, this only happens when I have debug logging enabled... That makes sense! ^^
Sorry, I'll close this one
