### ISSUE TITLE
Export egplugin file includes Thumbs.db

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#231]
Thumbs.db files are not getting removed during export of plugins.

EG 0.5 RC 2

**Comment by kdschlosser** [comment]
This we do know about. and for the life of me i cannot remember if the PR for the hidden/system files got added or not. but that PR is what fixes this problem

**Comment by ThomasBott** [comment]
Ah, sorry, didn't check that to be honest, I know there was one, I just thought it has been added...

**Comment by kdschlosser** [comment]
to be honest with ya I thought it had been as well. but i had to go and look also. LOL

**Comment by kdschlosser** [comment]
#146 fixes this issue and will be released with eg 0.6

**Comment by per1234** [comment]
If @ThomasBott is using EventGhost v0.5.0-rc2, shouldn't the issue already be fixed since #146 was merged before that release?

**Comment by kdschlosser** [comment]
it was merged into the development branch for EG 0.6
