### ISSUE TITLE
EG install hangs at Finishing

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#245]
The EG installation will hang at finishing unless you go in and end the EventGhost.exe process. This is caused if the user installing EG has been assigned to the Administrators group. 

If there would be someone willing to confirm this that would be a big help. but I do believe this is is related to #229 and I can incorporate the fix into #240 

I just need to confirm that this is in fact the error.

**Comment by topic2k** [comment]
fixed via #240
