### ISSUE TITLE
Add shortcut buttons for expand/collaps tree

### ISSUE THREAD

**Issue by topic2k** [EventGhost/EventGhost#282]
Add small buttons to the configuration tree (and tree's in other places) to expand/collaps the tree or the selected item (with subitems).

http://www.eventghost.net/forum/viewtopic.php?p=48661#p48661

**Comment by topic2k** [comment]
Pull Request #288

**Comment by kdschlosser** [comment]
I am working on redoing the context menus. It will only show what is allowed for a specific item. once I get the base idea done you can have at it for adding the items. now remember you are going to have to add graying out of the menu items if for example the specific tree is already fully expanded then you will want to gray out both the expand and expand all. but if only the selected item is expanded and not everything under it then you will gray out the expand and not the expand all..
