### ISSUE TITLE
Repository description points to eventghost.org

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#295]
Should be changed to eventghost.net:
![eg_description](https://user-images.githubusercontent.com/8572152/34704962-c6c4f418-f4b1-11e7-8e3f-03a96c61b0a7.png)
Someone with more elevated privileges in the repo will have to do this.

**Comment by topic2k** [comment]
Changed, TY

**Comment by kdschlosser** [comment]
@per1234 you the man 👍
