### ISSUE TITLE
slack problem

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#312]
there appears to be a problem with the slack icon and link on the github main page for the repo.

**Comment by dequi** [comment]
Well it is the service at https://eventghost-slackin.herokuapp.com that generates an error when requesting https://eventghost-slackin.herokuapp.com/badge.svg . Have you looked at the error log for the Heroku application?

**Comment by kdschlosser** [comment]
heyyyy dequi!!!! how the hell ya been????

**Comment by dequi** [comment]
I'm well, just trying to see where I could help out a bit, maybe starting with the v0.5 milestone issues.
You or @topic2k created this herokuapp, or is a remnant of a distant past that might need replacing?
