### ISSUE TITLE
Website/Forum Down

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#332]
I am aware the website and forum are down. I am quite mad about it actually. I went to pay the bill on the 15th of this month and was not able to due to a technical problem on their end. This problem still has not been fixed. I told them that the service should not get suspended because of a failure to pay due to an issue on their end. Well guess what. They suspended it. And of course no one in the billing Dept is there. I sent an email to the support department. They responded that the billing department will contact me. I sent a message back saying you think you can unsuspend my server in the meantime.

**Comment by topic2k** [comment]
:disappointed:
