### ISSUE TITLE
changelog is incorrect in new release.

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#333]
The named pipe has been swapped out for a socket connection.

I have not dug through and really looked but I do know that one off the top of my head.
That one is supposed to be there but it has been superseded but the PR for changing out the named pipe for the socket connection. maybe adding a (superseded) after things like that.

**Comment by topic2k** [comment]
you mean that the line with `NamedPipe.py: Add simultaneous connections #290 (kdschlosser)` don't needs to be in there?

**Comment by kdschlosser** [comment]
you can remove the line in the changelog. but the named pipe has been removed. to technically it has been superseded.
