### ISSUE TITLE
Plugin export (create egplugin file) not working

### ISSUE THREAD

**Issue by GruberMarkus** [EventGhost/EventGhost#334]
According to http://www.eventghost.net/forum/viewtopic.php?t=8219, running the command eg.PluginInstall.Export(eg.document.frame) in a script should open a GUI making it possible to export plugins in egplugin file format.

Running the code results in the following error:

10:59:01   Python Skript
10:59:01      DEBUG: 0 ActionThread: PluginInstall.Export(pluginInfo=<eg.Classes.MainFrame.MainFrame; proxy of <Swig Object of type 'wxFrame *' at 0x4e7ba28> >)
10:59:01      Traceback (most recent call last):
10:59:01        Python script "7", line 1, in <module>
10:59:01          eg.PluginInstall.Export(eg.document.frame)
10:59:01        File "C:\Program Files (x86)\EventGhost\eg\Utils.py", line 455, in LogItWithReturnWrapper
10:59:01          result = func(*args, **kwargs)
10:59:01        File "C:\Program Files (x86)\EventGhost\eg\Classes\PluginInstall.py", line 87, in Export
10:59:01          pluginData = self.GetPluginData(pluginInfo)
10:59:01        File "C:\Program Files (x86)\EventGhost\eg\Classes\PluginInstall.py", line 118, in GetPluginData
10:59:01          description = pluginInfo.englishDescription
10:59:01      AttributeError: 'MainFrame' object has no attribute 'englishDescription'

I could also not find a button or menu entry for plugin export as mentioned in the forum link.

**Comment by topic2k** [comment]
The information in the froum thread is wrong or outdated. `eg.PluginInstall.Export()` has to be called with a `eg.PluginModuleInfo` instance as parameter. For the installed plugins you can find them in the eg.pluginManager.database dict (with the guid of the plugin as key).

An easier way is to open the _Add plugin dialog_ and right click the plugin you want to export and then, well, click _Export_.
