### ISSUE TITLE
SchedulGhost does not store repeat interval

### ISSUE THREAD

**Issue by GruberMarkus** [EventGhost/EventGhost#335]
With EventGhost v0.50-rc5, SchedulGhost correctly stores the repeat type (day, week, month, ...), but not the repeat interval. It is displayed as "99999" when SchedulGhost Manager is opened.

**Comment by topic2k** [comment]
Can you give more information (copy/paste the macro, the SchedulGhost.xml)? I'm not really sure i understand where you see this (i'm not the author of this plugin, so i have to do some more analyzing of the code).

**Comment by GruberMarkus** [comment]
Attached, please find my SchedulGhost.xml and a screenshot, in which I marked the option which resets itself each time the dialog is opened.
[SchedulGhost.txt](https://github.com/EventGhost/EventGhost/files/2616643/SchedulGhost.txt)
![screenshot](https://user-images.githubusercontent.com/26838358/49030614-15f55700-f1a8-11e8-8a31-520e38d4a467.jpg)

**Comment by topic2k** [comment]
Thank you for the details. Found the problem. The fix will be in the next release. Meanwhile you can download the [changed file](https://github.com/EventGhost/EventGhost/blob/master/plugins/SchedulGhost/__init__.py) or change line 1129 from
`numCtrl.SetValue(str(data[3]))`
to 
`numCtrl.SetValue(data[3])`
