### ISSUE TITLE
File, Restart not working

### ISSUE THREAD

**Issue by GruberMarkus** [EventGhost/EventGhost#336]
In version 0.50-rc5, the command "File | Restart" no longer works. There is no error message, only the following debug output:
13:42:02   DEBUG: 0 Socket Server: new client
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:3: ---> EG - 'testcon'
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:3: connection closed
13:42:02   DEBUG: 0 Socket Server: new client
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: ---> EG - 'eg.document.ShowFrame, ()'
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: Command: eg.document.ShowFrame, Parameters:  ()
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: Document.ShowFrame()
13:42:02   DEBUG: 1 MainThread: MainFrame.Iconize(flag=False)
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: Document.ShowFrame => None
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: <---- EG - None
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: ---> EG - 'closecon'
13:42:02   DEBUG: 0 Socket Client: 127.0.0.1:4: connection closed

**Comment by topic2k** [comment]
uh, had a quick look at it, but i think this something for @kdschlosser.

**Comment by kdschlosser** [comment]
fixed in #340
