### ISSUE TITLE
Cannot trigger events after upgrade + can't register for forums

### ISSUE THREAD

**Issue by nobodyspecial** [EventGhost/EventGhost#349]
First off, I'm probably missing something simple but I tried to upgrade to the release candidate version and after the upgrade I cannot trigger any of the the events I have created. A box pops up that says "the root item, folders, and event can't be executed" when I try to execute any events. The macros that contain the events work fine though.

Second, I can't register for the forums. I get the message " Forbidden. Please enable JavaScript." I have javascript enabled.

**Comment by topic2k** [comment]
Can you post your configuration file (be sure to remove sensitive data)?

The message normally pops up when you try to manually execute a folder. Maybe somewhere in your configuration file there is an action that tries to execute a folder. Maybe running EG from command line with `-debug` parameter can give a clue.

**Comment by nobodyspecial** [comment]
Well it happens with the default config, not just my own. I tried to run the Mute event from the command line (didn't trigger) with the default config and here is the result. 

EventGhost.exe -debug -event Mute
`DEBUG: 0 Socket Server: new client
DEBUG: 0 Socket Client: 127.0.0.1:12: ---> EG - "eg.TriggerEvent, ('Mute', None)"
DEBUG: 0 Socket Client: 127.0.0.1:12: Command: eg.TriggerEvent, Parameters:  ('Mute', None)
Main.Mute
DEBUG: 0 Socket Client: 127.0.0.1:12: <---- EG - <eg.Classes.EventGhostEvent.EventGhostEvent object at 0x04CB52D0>
DEBUG: 0 Socket Client: 127.0.0.1:12: ---> EG - 'closecon'
DEBUG: 0 Socket Client: 127.0.0.1:12: connection closed`

This is EventGhost_0.5.0-rc5 on Win7x64. Everything works great on EventGhost_0.4.1.r1722

As for the forum, I've tried with different browsers, cleared cache and still no go. [This](https://i.imgur.com/dP7aKar.jpg) message appears after I hit submit on the account registration page.

**Comment by kdschlosser** [comment]
ok look down at the bottom of EG. there is a little checkbox.. make sure it is unchecked

![image](https://user-images.githubusercontent.com/10932297/50495916-8e3e7a80-09e9-11e9-9131-21280a957a42.png)

I am not sure what the issue you are having with the forum is. you might want to check the website specific security settings. or maybe a plugin is causing it.

**Comment by kdschlosser** [comment]
try the forums now. I cleared the cache. there have been reports of this happening and clearing the cache solved the problem

**Comment by nobodyspecial** [comment]
Forum registration worked. Thanks.

I upgraded to rc6 hoping for a fix but no luck. I also noticed another problem, I can't open the options window. Log shows:

> Traceback (most recent call last) (0.5.0-rc6):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\OptionsDialog.py", line 194, in Configure
    languageChoice.SetSelection(languageList.index(config.language))
ValueError: 'en_US' is not in list
  
Is there a dependency that this version needs that the previous stable does not?

**Comment by kdschlosser** [comment]
you need to uncheck that pain in the ass box at the bottom of EG. I will guarantee you the events are coming through. having that box checked off will cause the events to not show in the log. the only way an even will show in the log is if you have the event placed in a macro.



well now isn't that a curious error.

No matter on that error for the moment. we need to get the event issue sorted out first. and then we can go from there.

**Comment by kdschlosser** [comment]
we had to alter the language handling inside of EG due to a bug. and it is apparent that we have created a few in the process of changing it. we will get it sorted out. I am working on the language portions now as we speak. I am doing a complete rewrite of the language system.

**Comment by kdschlosser** [comment]
ok so from here I am going to want you to perform a completely clean installation of EG, Don't worry we are going to backup every single one of your settings.

close eventghost and save if necessary
open the Windows Explorer (File Explorer)
in the address bar at the top type in %appdata% and press enter.
In that folder there will be a folder named EventGhost. rename it and add .backup to the name.

back to the address bar
type in %programdata% and press enter.
add .backup to the name of the EventGhost folder,

back to the address bar.
type in %programfiles(x86)% and press enter (if that does not work navigate to where you install your x86 programs to

create a new folder called EventGhost.backup
go into the EventGhost folder. press ctrl+a then press ctrl+c
in the address bar at the top add .backup to the end of the address listed and then press enter
click on the empty white space in the right panel. then press ctrl+v this is going to copy you eventghost installation into this folder. 

I do not know where you saved your EventGhost configuration tree to. this you will have to locate and also make a copy of that file and add .backup to the end.
***IMPORTANT***
before continuing any of the steps below. verify that you have completed all steps above and also verify that all files/folders have been copied/backed up. once the steps below are completed if something is missing it is lost forever. so make sure you have everything backed up before continuing 

after you are done. then go to Control Panel --> Programs and Features
locate the EventGhost installation. right click on it then click on uninstall in the menu that appears.

after that is done go back to the Windows Explorer (File Explorer) window you were previously in.
click on the address bar at the top. remove EventGhost.backup from the end of the address and press enter
if there is an EventGhost folder listed in the panel on the left in the tree. left click it once then right click on it and then click on delete in the menu that appears.

go back to the address bar
type in %appdata% and press enter
you can now delete the EventGhost folder here (if there is one)

back to the address bar
type in %appdata% and press enter
you can now delete the EventGhost folder here (if there is one)

Now install EventGhost 0.5 RC6

after it is done installing run it to confirm the installation is good.
while it is running open up a command prompt and type in

    "%programfiles(x86)%\EventGhost\EventGhost.exe" -event Test.Event

**make sure you include the double quotes (")
and verify that an event is visible in EventGhost


let me know how this goes and then we will work from there and getting your backup data back into place.

MAKE SURE TO FOLLOW EVERY SINGLE STEP NOT SKIPPING ANY
we are not responsible for any lost/corrupted data.

**Comment by nobodyspecial** [comment]
I followed all steps, same result. If I right-click and execute a macro, it works, if I right-click and execute an action, it works. If I do that with an event the box pops up and says [this](https://i.imgur.com/zZmjJCJ.jpg). If I run it from the command line, nothing happens. If I try to open the options dialog I get this in the log window:

> DEBUG: 2 MainThread: Create(cls=<class 'eg.Classes.OptionsDialog.OptionsDialog'>)
DEBUG: 3 MainThread: OptionsDialog.ProcessingTask()
DEBUG: 3 MainThread: OptionsDialog.Configure(parent=<eg.Classes.MainFrame.MainFrame; proxy of <Swig Object of type 'wxFrame *' at 0x4ce7230> >)
DEBUG: 3 MainThread: OptionsDialog.__init__(parent=<eg.Classes.MainFrame.MainFrame; proxy of <Swig Object of type 'wxFrame *' at 0x4ce7230> >, title='Options')
DEBUG: 3 MainThread: OptionsDialog.__init__ => None
Traceback (most recent call last) (0.5.0-rc6):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Utils.py", line 455, in LogItWithReturnWrapper
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\OptionsDialog.py", line 194, in Configure
    languageChoice.SetSelection(languageList.index(config.language))
ValueError: 'en_US' is not in list
DEBUG: 2 MainThread: Create => <eg.Classes.OptionsDialog.OptionsDialog; proxy of <Swig Object of type 'wxDialog *' at 0x3dfdab8> >
DEBUG: 2 MainThread: OptionsDialog.GetEvent()
DEBUG: 3 MainThread: OptionsDialog.Destroy()
DEBUG: 3 MainThread: OptionsDialog.ProcessingTask => None
DEBUG: 2 MainThread: OptionsDialog.GetEvent => (None, None)

**Comment by topic2k** [comment]
You can't execute an event from the config tree. Instead you can execute the macro where the event is bind to.

The error with the options dialog is a bug (IMO). You can fix it if you edit `C:\Program Files (x86)\EventGhost\eg\Utils.py` and change line 318 from
```python
    return "en_US"
```
to
```python
    return "en_EN"
```

You said, when you run from commandline. nothing happens. Do you mean just running EG or start EG with the `-event` parameter? If latter: is the box at the bottom of the main window unchecked?

**Comment by topic2k** [comment]
Does the event not appear in the log window or does it not execute a macro? Be sure to notice that the mute event you send from command line is not the same as the system mute event (`Main.Mute` vs `System.Mute`).

**Comment by nobodyspecial** [comment]
log shows (box is unchecked):

>Main.Mute

It's not triggering the macro.

**Comment by topic2k** [comment]
But the event `Main.Mute` is added to the macro?


Can you please post a screenshot that shows the windows with event in the log window and the macro in config tree?

**Comment by nobodyspecial** [comment]
![zzmjjcj](https://user-images.githubusercontent.com/652026/50541101-f87b2a80-0b63-11e9-9132-d19384cb6eb9.jpg)
  
This is exactly what happens. Ignore the popup.

**Comment by nobodyspecial** [comment]
Ok I think I get it. In the previous stable version I could trigger any event from the command line and the macro would run. In this version triggering an event from the command line creates a new event that needs to be added to the macro. 

Thanks! I really appreciate the help, I doubt I would have figured it out on my own.

**Comment by topic2k** [comment]
Glad, we could help. And if you have more questions be sure to also visit our forum at [eventghost.net/forum](http://eventghost.net/forum/)

**Comment by kdschlosser** [comment]
I added back in the Bug label  because of the en_US bug in the language. we now Know what the problem is with that. An alteration needs to be made to the options dialog to fix the problem. it is because of the changes to the language system. which uses actual locale names. I am not sure where the en_EN came from originally because it is not really a locale. We need to have the options dialog work the same as the eg.Utils.GetClosestLanguage function. where if it cannot find a prefect match it will then check only the first 2 letters.
