### ISSUE TITLE
Changed "Trigger Event" behavior when event string contans a dot

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#350]
A significant breaking change was introduced by https://github.com/EventGhost/EventGhost/pull/279/commits/294f16bf838cb58962cec90d7628545293343c6a. 

Prior to that commit, this action:
```python
eg.plugins.EventGhost.TriggerEvent(u'foo.bar', 0.0, None, False, False)
```
would trigger the event `Main.foo.bar`. After the commit, the triggered event is `foo.bar`. The `Main.` is now only added when the event string does not contain a dot.

I previously reported this at https://github.com/EventGhost/EventGhost/pull/279#issuecomment-356185110. At that time, @kdschlosser's plan to fix this was:
>I can add a checkbox to enable or disable the Main prefix and have it set to off as a default.

But that still hasn't happened. In order to avoid having this issue get forgotten in a comment thread of a merged PR, I'm creating a dedicated issue.

**Comment by kdschlosser** [comment]
OOOOOkkkk sir. I forgot about that.. I am so sorry... I will correct that asap!

anyways.. how the hell ya been per??? haven't heard from you in a while. I hope work is good. and everything else is good. I will e-mail you in the next day or so to catch up.
