### ISSUE TITLE
Exepction when trying to open the options dialog on system with en_US locale, 0.5.0-rc6

### ISSUE THREAD

**Issue by thecode** [EventGhost/EventGhost#351]
**Describe the bug**
Exepction when trying to open the options dialog on system with en_US locale
 
**To Reproduce**
Steps to reproduce the behavior, something like:
1. Go to 'File'
2. Click on 'Options'
3. Error:
Traceback (most recent call last) (0.5.0-rc6):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\OptionsDialog.py", line 194, in Configure
    languageChoice.SetSelection(languageList.index(config.language))
ValueError: 'en_US' is not in list

**Expected behavior**
Options dialog should be displayed

**Additional context**
As a workaround I have changed line 84 in OptionsDialog.py from:
`        languageList = ["en_EN"]
`
to:
`        languageList = ["en_US"]
`
Options dialog opened successfully without any errors

**EventGhost version**
Software
Program Version: 0.5.0-rc6
Build Time: יום ב, 24 דצמ 2018 09:01:48
Python Version: Stackless Python 2.7.12 final 0
wxPython Version: 3.0.2.0

System
Operating System: Microsoft Windows 10 Professional, 64-bit (build 17134)

**Comment by kdschlosser** [comment]
can you do me a favor.. can you fix the code and submit a PR for it please. I would like for your name to appear in the changelog and also for the history of who has helped with the project.

**Comment by topic2k** [comment]
That was introduced in https://github.com/EventGhost/EventGhost/commit/9968f68ff4ffeee97404d40728b552aaf23f422e by @kdschlosser. Myabe he can remember why he changed it.

**Comment by kdschlosser** [comment]
the language systems needs a little TLC. because there is an issue in wxPython (wxWidgets) that incorrectly gets the locale I had to build a cross reference table. and to do that I had to use IETF language tags. which is a combination of the iso 639-1 language code and the iso 3166-1 Alpha2 Country code. this is pretty much the standard for having a language locale id's put together.


I think that the options dialog needs to have a once over. I have a funny feeling there is something else that is missing from it.

**Comment by kdschlosser** [comment]
question. did you happen to check out that language file I sent you?? I am wondering how the translation came out.

**Comment by thecode** [comment]
What I did is just a workaround, it doesn't solve the problem completely, the language selection box after will display a language with missing icon because of that.

**The system with the workaround:**
![image](https://user-images.githubusercontent.com/1858925/50736718-804adf80-11c9-11e9-82c7-97d9b2b1e362.png)

**System where the locale is not en-US:**
![image](https://user-images.githubusercontent.com/1858925/50736695-3530cc80-11c9-11e9-9172-811ca0a8880d.png)

As written above me, the problem is not related to the OptionsDialog.

@kdschlosser, I think I can track down a valid solution in the code, than I will issue a poll request for the change.


The options I think of are:
1. Change the en_US to en_EN or any other change which will treat en-US as English.
2. Add a system language "English - United States", but this will create two languages in the dialog UK & US.

**Comment by kdschlosser** [comment]
thats fine if there is multiple entries for the same language. because the setting of the language also sets the local.. so if you select en_UK then things like date format and currency will change with it

with the old language system EG did not change these things (unless you happen to be one of the lucky ones with de_DE and that is an actual real ITEF language code.

**Comment by kdschlosser** [comment]
what needs to be done is you need to take eg.config.language. and split the bugger on the underscore. and use the first 2 letters to compare against any files in the languages folder. and only the first 2 letters of the files names. 

[code]
languageNames = eg.Translation.languageNames
languageList = ["en_EN"]
for item in os.listdir(eg.languagesDir):
    name, ext = os.path.splitext(item)
    if ext == ".py" and name in languageNames:
        languageList.append(name)

languageList.sort()
languageNameList = []

for x in languageList:
    if x in languageNames:
        languageNameList += [languageNames[x]]
    else:
        for key in languageNames.keys():
            if key.split('_')[0] == x .split('_')[0]:
                languageNameList += [languageNames[key ]]
[/code]

that should handle any and all issues with the language bits of the option dialog.

**Comment by thecode** [comment]
> what needs to be done is you need to take eg.config.language. and split the bugger on the underscore. and use the first 2 letters to compare against any files in the languages folder. and only the first 2 letters of the files names.
> 
> ```python

> for x in languageList:
>     if x in languageNames:
>         languageNameList += [languageNames[x]]
>     else:
>         for key in languageNames.keys():
>             if key.split('_')[0] == x .split('_')[0]:
>                 languageNameList += [languageNames[key]]
> ```
> 
> that should handle any and all issues with the language bits of the option dialog.
That didn't work, it will add "English - United States" to the list, but since this language doesn't exist in the translations it picks up the wrong translation (Spanish in this case):
See bellow:
![image](https://user-images.githubusercontent.com/1858925/50754539-b7b79b80-125e-11e9-9cf7-e884db89365b.png)

![image](https://user-images.githubusercontent.com/1858925/50754692-390f2e00-125f-11e9-971c-59ec43e788fb.png)

I think that for now (unless re-writing the whole language mechanism) the simplest solution is to default to English for non-existing languages.
```python
        if config.language not in languageList:
           config.language='en_EN'
```

**Comment by kdschlosser** [comment]
you can give this a try. 

This is a complete rewrite of the whole language system. This version actually does not come bundled with any pre installed language files. It will do the translations for the core when EG loads. it also does the translations for plugins on the fly as they are installed (or run for the first time).

https://ci.appveyor.com/api/buildjobs/9sddy0jwj7x5iu7l/artifacts/_build%2Foutput%2FEventGhost_WIP-2019.01.06-15.23.56_Setup.exe

**Comment by thecode** [comment]
Notes about this version:
1. Installation gave an error, I didn't find anything in the log (attached)
[Log.txt](https://github.com/EventGhost/EventGhost/files/2735599/Log.txt)
2. The correct language is displayed, but the menu is oriented right to left instead of left to write.
![image](https://user-images.githubusercontent.com/1858925/50816536-9079d080-1329-11e9-8835-4326cc115b66.png)
3. It is not possible to close the menu with the "OK" button (program will hang), only "Cancel".

**Comment by kdschlosser** [comment]
what region of thee world are you located in? and what are the locale settings in windows set to?

**Comment by thecode** [comment]
![image](https://user-images.githubusercontent.com/1858925/50832807-fa10d380-1357-11e9-86dc-bb955affbd78.png)

The wrong right to left layout is caused by elements that are loading the default locale instead of the user selected one (see my fix at issue  https://github.com/EventGhost/EventGhost/issues/319#issuecomment-451778864)

**Comment by kdschlosser** [comment]
OK you already know about the right to left text. so that's good. the application handing I can handle give me a little bit of time.

if you do this in the time being to mess around with it.. go to %appdata%/eventghost open the config.py file

change the language line to read 

    language = None

then it will use the locale and language from windows.

Now I know the translations are going to bee crappy. But if they help you to understand what you are doing inside EG then it works as advertised. the language files can be altered

**Comment by molitar** [comment]
Thanks for posting that work around.. at least I can now use EventGhost as even RC5 did not work.

**Comment by beau76** [comment]
what is the best fix to get around this error

**Comment by milothomas** [comment]
> OK you already know about the right to left text. so that's good. the application handing I can handle give me a little bit of time.
> 
> if you do this in the time being to mess around with it.. go to %appdata%/eventghost open the config.py file
> 
> change the language line to read
> 
> ```
> language = None
> ```
> 
> then it will use the locale and language from windows.
> 
> Now I know the translations are going to bee crappy. But if they help you to understand what you are doing inside EG then it works as advertised. the language files can be altered

language = None didn't work for me on v0.5.0-rc6, instead language = 'en_EN' did the job.

**Comment by kdschlosser** [comment]
There is a nightly build that has this issue fixed. There is nothing I can do about the right to left text as this is an internal issue with the GUI framework. I believe that issue has been addressed but in order to upgrade to that version of the GUI framework it is going to require a massive amount work to do. It is on the "todo" list and it will be done when we do an upgrade to Python 3.x. I am working on the plugin repository so we can facilitate an easy way for users to get an updated version of  plugin that will work with the new GUI framework and Python 3.x Things have to be done in a very specific order to make this process as seamless as possible for the users.

**Comment by molitar** [comment]
> 
> 
> There is a nightly build that has this issue fixed. There is nothing I can do about the right to left text as this is an internal issue with the GUI framework. I believe that issue has been addressed but in order to upgrade to that version of the GUI framework it is going to require a massive amount work to do. It is on the "todo" list and it will be done when we do an upgrade to Python 3.x. I am working on the plugin repository so we can facilitate an easy way for users to get an updated version of plugin that will work with the new GUI framework and Python 3.x Things have to be done in a very specific order to make this process as seamless as possible for the users.

I am really glad to hear that.  Keep up the great work!
