### ISSUE TITLE
'OK' button is grayed in configuration popup when trying to add some plugins

### ISSUE THREAD

**Issue by Drumaster78** [EventGhost/EventGhost#357]
**Describe the bug**
Adding plugins seems to be partially broken for me in rc5 and rc6 version as 'OK' button is not active (grayed) when adding a new plugin. I realized this only now because I added all my plugins previously in rc4. Works fine in rc4 and 0.4.1.r1722.
Some other plugins like 'Generic HID' will make the app freeze if we 'ungray' the 'OK' button by checking/unchecking an option (seems to be because we can then push 'OK' button without having selected a HID device through the plugin configuration window).

**To Reproduce**
1. Install rc5 or rc6
2. Try to add 'Keyboard' plugin (in 'Input Devices' section) for instance
3. Notice that the 'OK' button is grayed in the plugin window
4. Just uncheck the option 'Universal modifiers' in the window
5. Notice that you can now add the plugin

**Expected behavior**
'OK' button should be clickable as soon as plugin popup opens

**Configuration tested**
Windows 10 Professional (English language) build 1809

**Video**
[adding_plugins_rc5-rc6.zip](https://github.com/EventGhost/EventGhost/files/2732139/adding_plugins_rc5-rc6.zip)

**Comment by kdschlosser** [comment]
this is not a bug it is by design.
We want to make sure that the user has properly read an adjusted any configuration options that need to be made.

The reason for this is we have had users just "press the ok button" and then submit bug reports for non functioning components of EG as well as for the plugins. so doing that ensures that if there are any configuration changes that need to be made that they make them. if a plugin or an action has no configuration options you will not get a dialog that opens

**Comment by Drumaster78** [comment]
IMHO, it's a very bad design as it simply seems to be broken, as it's very confusing for the user and he won't guess what you intend to do about that. At least you have my opinion, do what you want with it. :)

Anyway, the fact to be able to validate the plugin configuration popup without selecting anything (see the issue related to the General HID plugin) leads to an app freeze, which is for sure a severe issue and not an expected scenario, so not something by design.

**Comment by kdschlosser** [comment]
we are discovering this is possibly going to cause a larger issue not having the OK button.

The problem we are tripping over with this thing is that the original way EG was designed is that there are "default" parameters that need to be supplied to the config dialogs. and the default parameters that some of the authors have supplied do not allow the program to operate correctly if they are left unchanged.

so the question is how to we make sure the user changes what needs to be changed but also allow the config dialogs hat have valid default values still work properly.

Now I do believe that there is an Apply button as well. and that is not grayed out. and if you press that Apply button then the OK button will become available to click on. I made this change a while ago. and o be honest I would have to go and look to see exactly what I did.. If you can double check that for me that would be a very large help. I want to make sure that is available. it could be there is a setup of the dialog I may have missed and that button is not available

**Comment by Drumaster78** [comment]
Just checked and the 'Apply' button is grayed as well as the 'OK' one. At least for the 2 plugins I tried above. Maybe you could just fix that second point, that would be still better than before. :)

**Comment by kdschlosser** [comment]
HMM now that my friend is a bug..
gonna have to do some digging into that and find out why.
