### ISSUE TITLE
Regional Format English (Germany) results in locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by Christoph-Wagner** [EventGhost/EventGhost#369]
**Describe the bug**
Upon installing EventGhost, I get an error and the option to open the log, the same happens on uninstall or trying to start EventGhost. EventGhost doesn't start (but uninstalls or installs (apparently) correctly)

```
Traceback (most recent call last):
  File "EventGhost.pyw", line 53, in <module>
  File "C:\Program Files (x86)\EventGhost\eg\__init__.py", line 31, in <module>
    import Cli
  File "C:\Program Files (x86)\EventGhost\eg\Cli.py", line 34, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "locale.pyc", line 581, in setlocale
locale.Error: unsupported locale setting

```

**To Reproduce**
Steps to reproduce the behavior, something like:
1. Go to Windows Settings -> Time & Language -> Region
2. Under Regional Format, choose *English (Germany)*
3. Try to install/start EventGhost

**Expected behavior**
Allow usage.

**Additional context**
Windows 10 Pro Version 1809 Build 17763.253

I realize I have a somewhat rare setup. My keyboard layout is *US International*, Region *Germany*, Regional Format *English (Germany)* and I made additional changes to the data formats (like having an ISO date).

My workaround for now is to set the Regional Format to *English (United States)* and change all the data formats to fit with what I want. I'm not sure I can leave it like this though as I think I remember having other problems pop up with that format (my machine is used for developing apps)

**EventGhost version**
Tested with v0.5.0-rc6 and v0.4.1.r1722, error is the same but 0.4 has slightly different line numbers in the log.

**Comment by Christoph-Wagner** [comment]
I'm not sure why the region matters.

Doing `locale.setlocale(locale.LC_ALL, '')` works fine and results in `'English_United States.1252'`

And `locale.localeconv()` returns my settings:

```
{
    'int_curr_symbol': 'USD',
    'currency_symbol': '€',
    'mon_decimal_point': '.',
    'mon_thousands_sep': ',',
    'mon_grouping': [3, 0],
    'positive_sign': '',
    'negative_sign': '-',
    'int_frac_digits': 2,
    'frac_digits': 2,
    'p_cs_precedes': 1,
    'p_sep_by_space': 0,
    'n_cs_precedes': 1,
    'n_sep_by_space': 0,
    'p_sign_posn': 3,
    'n_sign_posn': 0,
    'decimal_point': '.',
    'thousands_sep': ',',
    'grouping': [3, 0]
}
```

**Comment by kdschlosser** [comment]
here is the code from local.setlocale.

I guess my question is gong to be why are we passing an empty string to it??? maybe this is what is goofing it up??


```python
def setlocale(category, locale=None):

    """ Set the locale for the given category.  The locale can be
        a string, an iterable of two strings (language code and encoding),
        or None.

        Iterables are converted to strings using the locale aliasing
        engine.  Locale strings are passed directly to the C lib.

        category may be given as one of the LC_* values.

    """
    if locale and not isinstance(locale, (_str, _unicode)):
        # convert to string
        locale = normalize(_build_localename(locale))
    return _setlocale(category, locale)
```

**Comment by Christoph-Wagner** [comment]
The empty string is supposed to make it use the system default locale, so exactly what's wanted here I guess? I'll have a look at the EventGhost code tomorrow and see if I can find the problem, but I don't really know python ;)

**Comment by kdschlosser** [comment]
Now what we can do. I can list off the locales that are installed on the system and we can give the user the option of selecting which one to use in the event this error happens.  The issue I think we are going to have with that is that you specifically are running a custom language/locale setup. which python has no concessions for. we would need to code in the setting of the below information based on what we are able to retrieve from windows.

```python
{
    'int_curr_symbol': 'USD',
    'currency_symbol': '€',
    'mon_decimal_point': '.',
    'mon_thousands_sep': ',',
    'mon_grouping': [3, 0],
    'positive_sign': '',
    'negative_sign': '-',
    'int_frac_digits': 2,
    'frac_digits': 2,
    'p_cs_precedes': 1,
    'p_sep_by_space': 0,
    'n_cs_precedes': 1,
    'n_sep_by_space': 0,
    'p_sign_posn': 3,
    'n_sign_posn': 0,
    'decimal_point': '.',
    'thousands_sep': ',',
    'grouping': [3, 0]
}
```

es the use of EG is growing.. we are starting to see issues arise with the languages and locale. We are going to need to really dive into this and correct these problems. locale has to be the single hardest thing to deal with I think. there is no rock solid standardization of it that everyone follows. and then throw in the user being able to set up custom locale information.. Oh boy!,.. 

I know how to handle getting any required information from Windows. what I do not know how to handle is setting python up properly with the needed information. the locale module is written as a c extension I am going to have to read the source code for python and locate the code for it. to see exactly what we can manipulate. 

This is going to take some time.

**Comment by kdschlosser** [comment]
I am not sure the empty string is what is supposed to be passed. I would think that None would be passed. it does not state what an empty string does. 

there is also this little tidbit that gets setup if there is an import error of the extension module

``python
    def setlocale(category, value=None):
        """ setlocale(integer,string=None) -> string.
            Activates/queries locale processing.
        """
        if value not in (None, '', 'C'):
            raise Error, '_locale emulation only supports "C" locale'
        return 'C'
```

here you see the string being empty but again it does not state what it does. This setlocale is only there for an import error of _locale so the program will stay running and nothing more.

**Comment by kdschlosser** [comment]
now here is a wingdinger 

```python
import _locale

print _locale.__doc__
```
this prints out
> Support for POSIX locales.

I do know that pythons support for Windows is very limited (and not updated or repaired). So we might have to do exactly what I mentioned above and write a whole new locale module for python if we want it to operate properly.

**Comment by kdschlosser** [comment]
now.. here is anotheer thing..

https://docs.microsoft.com/en-us/cpp/c-runtime-library/language-strings?view=vs-2017

this lists off the supported windows language-locale codes. I  do not see `en_DE` available.

**Comment by kdschlosser** [comment]
ok so I found what the empty string is supposed to do



> A locale argument value of C specifies the minimal ANSI conforming environment for C translation. The C locale assumes that every char data type is 1 byte and its value is always less than 256. If locale points to an empty string, the locale is the implementation-defined native environment.

**Comment by kdschlosser** [comment]
I am thinking we are going to have to create a custom locale module to properly handle windows custom locales in order to handle this problem. I have to do some research on how to set the specific locale settings in python to match what is in Windows.

**Comment by kdschlosser** [comment]
I  just created a python version of the \um\WinNls.h file from the latest Windows 10 SDK
It will give a help in locating any needed functions/ structures and constants needed to possibly repair this problem.

https://github.com/kdschlosser/pyWinAPI/blob/master/um/winnls_h.py

**Comment by kdschlosser** [comment]
I can write a replacement for locale, and that replacement would be able to handle custom settings. But if i don't have to I would rather not.

**Comment by kdschlosser** [comment]
one other thing...

I do not have an English (Germany) choice in my format list

![image](https://user-images.githubusercontent.com/10932297/51888938-3c28a600-2355-11e9-9e41-3fb61db73e83.png)

**Comment by topic2k** [comment]
> OK so after more research and reading.. and searching.. I am now questioning why are we even setting the locale in Python.. the only way it gets used is when you use locale.str(). I do not believe it does anything other then that. and we do not use locale.str() anywhere in the EventGhost core. str() does not get replaced with locale.str() in the code for locale and we do not do it either.
> 
> So I guess the question is.. why are we setting the locale?

because we want to get the right values wx.Locale().GetInfo(wx.LOCALE_DECIMAL_POINT) for example. Otherwise it would result in wrong values IIRC.


I found a way to [workaround](#370) which seems to be working for me. Tested with regional format set to 'English (Germany)' and 'German (Germany)'.

**Comment by topic2k** [comment]
Hmm, strange. Did you change your region settings? I've set mine to English (Germany) and still get the error.
<img width="372" alt="2019-02-08 12_32_34-einstellungen" src="https://user-images.githubusercontent.com/6463113/52476349-9409ad00-2b9e-11e9-8072-c30c81ad8384.png">
<img width="620" alt="2019-02-08 12_33_00-administrator_ c__windows_system32_cmd exe - py" src="https://user-images.githubusercontent.com/6463113/52476358-9a982480-2b9e-11e9-8eda-6ae0d959e4c4.png">

My [workaround](https://github.com/EventGhost/EventGhost/pull/370) at least makes EventGhost runable, so i don't know if it has impact on places where locale setting are used.

**Comment by kdschlosser** [comment]
I will write a replacement that is not dependant on a locale or region. It will simply get the appropriate decimal settings from windows. We can do that. That is the only thing that locale does. I will also make a str replacement like the locale module has. And it will pass the string to Windows and Windows will do the conversion. This is what should have been done in the locale module but I am guessing this is not the case. Submitting a bug report to CPython is a complete joke. They don't fix windows related problems. They seem to only care about Linux. Once they got it so that python would run on windows (to increase it's popularity most likely) they pretty much stopped any development on the windows side of things.

It's extremely aggravating when there are bug reports from python. 2.3 that still exist in python 3.7 and I am talking about trivial things like constants having the wrong value. Something that would take all of 5 seconds to fix. They simply are more interested in releasing another version. That carries more bugs that never get fixed than the previous. wxPython and wxWigets is the same way. 

If I knew more web languages I would be really pushing to remove wxPython. 

pywin32 is another

I do know how to compile python. If we wanted to go that route and repair any broken code and compile our own version.

**Comment by kdschlosser** [comment]
I think I may have found a very simple solution to the problem here..
if you want to check out #373 and let me know if it fixes your issue it would be very helpful.

Thanks again.

**Comment by Christoph-Wagner** [comment]
Hey, thanks. I had changed my region to en_US and customized it to behave as I want it and still have event ghost work. Changed it back for the test and now it works :)

**Comment by kdschlosser** [comment]
no worries m8. had to track down the exact problem.
