### ISSUE TITLE
Appveyor problem? 

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#372]
https://ci.appveyor.com/project/topic2k/eventghost/

![image](https://user-images.githubusercontent.com/10932297/52903526-f0428180-31db-11e9-8023-a1d4139cf0d0.png)

**Comment by topic2k** [comment]
https://ci.appveyor.com/project/EventGhost/eventghost

**Comment by kdschlosser** [comment]
ahhh OK. I need to change the build button on the forum then.. If i can remember how to.. :smile:
