### ISSUE TITLE
Still can't sign up on forum

### ISSUE THREAD

**Issue by theplasticbling** [EventGhost/EventGhost#381]
This is kind of in response to this issue: https://github.com/EventGhost/EventGhost/issues/344

Sorry I haven't been able to check in, been extremely tied up with work and had to put the project I'm working on to the side. Now that I have some free time, I'd like to sign up to the forum. I'd also like to report that the on shutdown command seems to work, but I haven't tried it without the Windows Shell running yet. Hoping to try that here soon and will update you!! On a side note, I'd like to request a plugin to turn on/off HDR and WCG on Windows 10 and also detect when it gets turned on and off. It would complete the setup I have

**Comment by kdschlosser** [comment]
what is the issue with logging into the forum?
what are you getting for an error message?

what is HDR and WCG??
