### ISSUE TITLE
Website is down....

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#383]
As you can tell the website is down. And it's not coming back up either. Host just up and closed their doors. I can't even get to our data. I do have a backup of the database. I am in the proces of migrating to a new SSD on my personal machine. I deleted the last backup I had. and then not even 24 hours later.... POW.

So I do not even have a backup of the website. I have to check one place I may have a backup there.
I am really pissed about this. It is really only the attachments I do not have.

I do have all of the plugins. well almost all of them.

I am most likely going to have to wait until Monday to get the website back up and running. 
I am going to go for the gold and get a dedicated server.... It's only money right?

**Comment by kdschlosser** [comment]
I secured a server. 24-48 hours for setup time, This is a dedicated server. No one else is on the thing. it's just us. If anyone happens to know anyone that would be interested in splitting the bill. There is more then enough resources.

CPU: AMD 6 cores @ 3.5 GHZ
RAM: 8GB
DISK: 120 GB SSD
UPLINK: 1000MBit
BANDWIDTH: 33TB
IP ADDRESSES: 5@ IPv4
IP/KVM: Upon request

**Comment by kdschlosser** [comment]
well that was fast. only took them an hour to get the server up and running. 

I am running some tests to see if everything is up to snuff.

LAST HOST: UPSTREAM 15Mbit/sec, DOWNSTREAM 40Mbit/sec
INTERNET SPEED TEST
Testing download speed................................................................................
Download: 931.63 Mbit/s
Testing upload speed................................................................................................
Upload: 777.36 Mbit/s

OK so that is an extremely large difference.

LAST HOST: READ AND WRITE < 20MB/sec

WRITE SPEED
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.22531 s, 254 MB/s

CACHED READ SPEED
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.202891 s, 5.3 GB/s

READ SPEED
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.15448 s, 258 MB/s

OK big change there as well..


Memory is the 8gb. And there are 6 cores. I am using almost no ram. only 95 MB. I know it wasn't like that with the last host. and the CPU cores are showing 0.0% across the board. last host the thing was almost always at 20% or higher. (10% with just an OS install like this is right now.)

**Comment by fuqit** [comment]
Kevin
I'd like to help out.  Any idea of expenses yet?

**Comment by monkmochi** [comment]
Hello kdschlosser 

I am grateful to the author for EventGhost. Your software has been helpful and interesting for me. I am not a programmer of any sort and this software provides abilities absent of a person without such skill or knowledge. 

I have an inquiry for response at your convenience. I realize that more important matters are currently prevalent and expect no immediate response to my inquiry.  

A button pressed causes repeating events until the button's release. Can EventGhost filter those succeeding events to prevent repeated actions?

With humble appreciation, 

Monk Mochi

**Comment by monkmochi** [comment]
Hello again, 

I was searching archive dot org for previous versions of the EventGhost website. The fallowing is the latest date I could load without a blank page with the text "page ok" posted in the top left corner or a loading error.  Perhaps, it may be of some use to your recovery everts. 

https://web.archive.org/web/20170512014503/http://www.eventghost.org:80/

With humble appreciation, 

Monk Mochi

**Comment by kdschlosser** [comment]
Yes I have gotten as much as I can from the archives. I still do not have the forum attachments as the archival process does not burrow into a forum and grab all the attachments and forum posts. I do have the forum posts. I do not have the attachments.

I do thank you for the help. It is appreciated. I do have the site back up. there are some things that need to be fixed. and I am still working on the forum end of things. But it shouldn't be long before I have the forum back up and operational minus the attachments.

**Comment by kdschlosser** [comment]
as far as your first post is concerned.

I would need some more information.

A what plugin are you using that is creating the events?
What kind of a device is causing the events to occur.

You can use the timer plugin in most cases to help with a problem like this. (If I am understanding the problem correctly)

You would set up a macro. in that macro you place the event that is to run the macro. then you place whatever actions in there that you want run. then add the Disable action. point it to the macro that the action is in. then Add the action from the timer plugin. 

create another macro in that macro add an event of "Timer.Enable.Macro" for example.
then add the Enable action. point it to the same macro that the Disable action is pointed to.

in the setup for the timer action you should be given the options of setting the duration (time to wait before firing an event) and also the event you want to have triggered. there will be some other options in there as well for repeating the event and things of that sort. you want to only run this event a single time. The duration is how long after the first button is pressed do you want to wait before a second one can be pressed you will need to tinker about with it to get the timing correct for your needs. Whatever event you set in this action is the same event you will use in the second macro (the one with the Enable action).


so what is going to happen when this runs is this. the event for the button press comes in. the macro then runs. at the end it is going to disable it's self so no further events will run the macro. it is also going to start a timer. when that timer expires an event is going to occur that will run the second macro. the second macro is then going to Enable the first on so it can run when the next button press event gets generated.

**Comment by monkmochi** [comment]
Good evening KDSchlooser,

Your reply is both appreciated and helpful. A timer which can continue within a disabled macro is excellent. I can set a name.of.button.event.* to trigger events within the button group and disable the folder containing all of the reaction macros. The repetitions range from 2 to 4 within the duration of a button press and release. 

I am using the General purpose HID plugin to read a compatible bluetooth Nintendo Switch controller. Eventghost recognizes the device without issue. Resolving the repetitious nature of the buttons seemed to be the most feasible solution for utilizing this controller. While I can not utilize the payloads of the axes events to discern direction, the 14 remaining buttons are a suitable quantity for controlling a DVD video within VLC. 

Your software is amazing. I first used it to remap a MacBook IR device. The controller's functions would alter when VLC had focus. I later added a screen menu and a set of macros which preserved the operation of an application. If the application's process was "destroyed", event ghost would restore it. 

With humble gratitude,

Monk Mochi

**Comment by kdschlosser** [comment]
If you post me the payload of the movements of the analog portions of the controller I can probably tell you what it is exactly doing.

You will need to move each analog control in this order and copy and paste all of the events from them.

* UP
* UP RIGHT
* RIGHT
* DOWN RIGHT
* DOWN 
* DOWN LEFT
* LEFT
* UP LEFT

basically starting in the up position and moving the control around in a circle clockwise stopping when you are up again.

please make sure you separate each analog control

you can copy and paste the event by selecting the first event then pressing and holding the left shift key and selecting the last event. then press ctrl+c to copy them. then paste them here into a post.

**Comment by kdschlosser** [comment]
@fuqit 

I am sorry I missed your post there. While I really do appreciate the offer.. unless you are a web developer there is not much you can do at this point. I am slowly plugging away at the database. It's simply time consuming to do and boring as hell.

**Comment by monkmochi** [comment]
Good Morning Kdschlooser,

I recently installed the 2019 Windows 10 version and EventGhost now has issues with the compatible bluetooth Nintendo Switch controller. I have installed the trial version of ReWASD and utilized it's virtual Xbox360 device for this reply. The actual Nintendo compatible device and the Virtual Xbox360 device use identical name and payload conventions. The fallowing events are form the virtual Xbox360.  


-Event list Start-

Left Stick : Up = HID.Value.0 3
Left Stick : Down = HID.Value.0 65532

Left stick : Left = HID.Value.1 5
Left Stick : Right = HID.Value.1 65530

Right Stick : Up = HID.Value.2 22
Right Stick : Down = HID.Value.2 65513

Right Stick : Left = HID.Value.3 63
Right Stick : Right = HID.Value.3 65472 

Direction Pad : Centered = HID.Value.15 0
Direction Pad : Up = HID.Value.15 1
Direction Pad : Up Right = HID.Value.15 2
Direction Pad : Right = HID.Value.15 3
Direction Pad : Down Right = HID.Value.15 4
Direction Pad : Down = HID.Value.15 5
Direction Pad : Down Left = HID.Value.15 6
Direction Pad : Left = HID.Value.15 7
Direction Pad : Left Up = HID.Value.15 8

All Button Names: HID.Button.(numerical value)

Examples: 
Button B = HID.Button.5
Button A = HID.Button.6
Button Y = HID.Button.7
Button X = HID.Button.8

-Event List End-


EventGhost version 5 seems to be in development and posts errors in the log instead of opening its preferences. The Ghost icon is a nice addition. Version 4 is suitable with the virtual Xbox360 device while version 5 matures. Your new Website is delightful. 

With humble respect, 

Monk Mochi

**Comment by fuqit** [comment]
Kevin
I didn’t post that.  Not sure who it was

Sent from my iPhone

On May 23, 2019, at 6:58 PM, Kevin Schlosser <notifications@github.com<mailto:notifications@github.com>> wrote:


as far as your first post is concerned.

I would need some more information.

A what plugin are you using that is creating the events?
What kind of a device is causing the events to occur.

You can use the timer plugin in most cases to help with a problem like this. (If I am understanding the problem correctly)

You would set up a macro. in that macro you place the event that is to run the macro. then you place whatever actions in there that you want run. then add the Disable action. point it to the macro that the action is in. then Add the action from the timer plugin.

create another macro in that macro add an event of "Timer.Enable.Macro" for example.
then add the Enable action. point it to the same macro that the Disable action is pointed to.

in the setup for the timer action you should be given the options of setting the duration (time to wait before firing an event) and also the event you want to have triggered. there will be some other options in there as well for repeating the event and things of that sort. you want to only run this event a single time. The duration is how long after the first button is pressed do you want to wait before a second one can be pressed you will need to tinker about with it to get the timing correct for your needs. Whatever event you set in this action is the same event you will use in the second macro (the one with the Enable action).

so what is going to happen when this runs is this. the event for the button press comes in. the macro then runs. at the end it is going to disable it's self so no further events will run the macro. it is also going to start a timer. when that timer expires an event is going to occur that will run the second macro. the second macro is then going to Enable the first on so it can run when the next button press event gets generated.

**Comment by kdschlosser** [comment]
@fuqit 

Odd then someone must have your login information or access to your computer.

I would check into that..

**Comment by kdschlosser** [comment]
@monkmochi 

the payload values we can do a simple remap to create events that can be used in a manner that you would be able to identify

you will need to create a macro in that macro you will need to create an event with `HID.Value\*`
then create a python script action and in that action place the code below. I commented the hell out of the script. It would be beneficial for you to read the comments. It is going to create a series of new events that begin with `Controller.`. the joysticks I did a conversion of the information. this conversion is a wee bit complicated but it converts to what would be needed if you wanted to control the mouse movement from the joystick.

Let me know if something is not working properly. as far as the joystick is concerned please do not marry it to an event just yet. I want you to copy all events that are generated HID and Controller events alike when you move the joystick. I need to make sure the math is correct.


```python
# the joystick movements are only going to produce an event for left stick and 
# an event for right stick. there is going to be a payload attached to those 
# events the payload consists of 
# (direction in degrees, init speed, max speed, acceleration)
# this is what is needed if you want to translate the joystick movements directly
# to mouse mouse movements.
# so if you wanted the left joystick to move the mouse create a macro add the 
# event for the left joystick
# then add a python command action with the following line put into it.

# eg.plugins.Mouse.GoDirection(*eg.event.payload)

# this should move the mouse. I am going to need to tweak this so let me know
# if it is not working up to snuff.

# wiggle_room is a percentage of the total range of
# motion of the analog joysticks. analog joysticks are not exact so there
# needs to be padding to know when it has moved the full amount or not. or
# when it is centered. we do not want this thing spitting out events all crazy
# like if you simply pick up the controller and the joysticks shake a little.
# this number you will have to tweak to get it perfect to eliminate those
# kinds of side effects.
WIGGLE_ROOM = 5.0

# this is the button mapping. You need to add the number that is in the event
# along with the coorsponding button. once you do that then all buttons will
# then be populated and correct events will be produced for them.
BUTTON_MAPPING = {
    '5': 'B',
    '6': 'A',
    '7': 'Y',
    '8': 'X'
}

DPAD_MAPPING = {
        0: 'Center',
        1: 'Up',
        2: 'UpRight',
        3: 'Right',
        4: 'DownRight',
        5: 'Down',
        6: 'DownLeft',
        7: 'Left',
        8: 'UpLeft'
    }

import math

def remap(value, old_min, old_max, new_min, new_max):
    old_range = old_max - old_min
    new_range = new_max - new_min

    return (
        (((value - old_min) * new_range) / old_range) + new_min
    )

button = eg.event.string.split('.')[-1]
payload = eg.event.payload

eg.globals.last_event = getattr(eg.globals, 'last_event', None)


if int(button) < 5:
    wiggle_room = WIGGLE_ROOM / 100.0

    padding = 65535.0 * wiggle_room
    center = 65535.0 / 2

    left_start = up_start = center - padding
    right_start = down_start = center + padding

    if button in ('0', '1'):
        suffix = 'Left.Joystick'
        x, y = getattr(eg.globals, 'left_joy', [0, 0])
        
    elif button == ('2', '3'):
        suffix = 'Right.Joystick'
        x, y = getattr(eg.globals, 'right_joy', [0, 0])
        
    else:
        suffix = ''
        payload = None
        x, y = [0, 0]
        eg.StopMacro()
        eg.Exit()

    if button in ('0', '2'):
        if payload <= left_start:
            new_x = remap(payload, 0, 32767, 32767, 0)
            init_speed = (new_x / 32767) * 100
            max_speed =  init_speed * 100
            new_x = -new_x
            new_y = y
            y = 0
        elif payload >= right_start:
            new_x = remap(payload, 32767, 65535, 0, 32767)
            init_speed = (new_x / 32767) * 100
            max_speed = init_speed * 100
            new_y = y
            y = 0
        else:
            new_x = x
            new_y = y
            init_speed = 0
            max_speed = 0
    else:
        if payload <= up_start:
            new_y = remap(payload, 0, 32767, 32767, 0)
            init_speed = (new_y / 32767) * 100
            max_speed = init_speed * 100
            new_y = -new_y
            new_x = x
            x = 0

        elif payload >= down_start:
            new_y = remap(payload, 0, 32767, 32767, 0)
            init_speed = (new_y / 32767) * 100
            max_speed = init_speed * 100
            new_x = x
            x = 0
        else:
            new_x = x
            new_y = y
            init_speed = 0
            max_speed = 0

    radians = math.atan2(new_y - y, new_x - x)
    degrees = math.degrees(radians)

    dist = math.hypot(new_x - x, new_y - y)
    accel = int(round(((dist / 32767) * 10)))
    
    payload = (degrees, init_speed, max_speed, accel)
    
    if init_speed == 0:

        new_x = 0
        new_y = 0
        
    if button in ('0', '1'):
        eg.globals.left_joy = [new_x, new_y]
    
    else:
        eg.globals.right_joy = [new_x, new_y]


elif button == '15':

    if payload in DPAD_MAPPING:
        suffix = 'DirectionPad.' + DPAD_MAPPING[payload]
        payload = None
    else:
        payload = None
        suffix = ''
        eg.StopMacro()
        eg.Exit()

elif button in BUTTON_MAPPING:
    suffix = 'Button.' + BUTTON_MAPPING[button]

else:
    payload = None
    suffix = ''
    eg.StopMacro()
    eg.Exit()
    
eg.TriggerEvent(prefix='Controller', suffix=suffix, payload=payload)
```

**Comment by adamcaz** [comment]
Happy to help @kdschlosser where I can. 

I’m pretty handy with a database restore for web apps - had to do a few when I had a hosting company fall over on me a few years back.

Willing to contribute to your hosting too if you want to message me some of the costs. 

I’ve been using your software for, I think, about 10yrs on my central Mediacenter so want to contribute to get you back up and running where I can.

**Comment by kdschlosser** [comment]
@adamcaz The database is not so much of an issue. what i can use a hand with is the website. I am not efficient in javascript, php, html and css. someone that is this would probably be a breeze. I am having to learn as i go. as far as helping for the hosting. I am all for that. The server is 50.00 USD a month. It is not that bad but it sure is a far cry from the 12 a month we were spending. once I get the forums back up and running we can talk more. github is not the best outlet for those kinds of conversations.


which reminds me. this is going to be a better way to go about supplying any kind of support until that time comes.

https://join.slack.com/t/eventghost/shared_invite/enQtNDYwMDU1OTE0ODY1LWUxMGY2MGY3OTNiNmIxZDBiYTQwOTQ1NjJiNmVmN2EyYWVlMjg4MzUwYTU3ZGViZTQyOTg3OGU4ZTA2N2MxMzk


the link above is for slack chat. it will be easier to handle any issues on there.

**Comment by kdschlosser** [comment]
OK the forum is back up and running. YAY!!!. The attachments are no longer available. I am going to see if there is a way to possibly locate them on the internet.because the attachments are a download there might be a way to locate them.
