### ISSUE TITLE
The process watcher plugin is constantly consuming ~7% CPU

### ISSUE THREAD

**Issue by binarynoise** [EventGhost/EventGhost#384]
**Describe the bug**
The process watcher plugin is constantly consuming ~7% CPU

**To Reproduce**
Open eg, add plugin and start it.

**Expected behavior**
When nothing happens the CPU should go idle

**Additional context**
Nearly all of the 7% are Kernel time. 

**Plugin version**
Process Watcher 1.0 and 1.1

**EventGhost version**
Software
Program Version: 0.5.0-rc6
Build Time: Mo, 24 Dez 2018 09:01:48
Python Version: Stackless Python 2.7.12 final 0
wxPython Version: 3.0.2.0

System
Operating System: Microsoft Windows Home, 64-bit (build 1809)
CPU: AMD A8-7410 APU with AMD Radeon R5 Graphics    
RAM: 7113 MB

**Comment by ThomasBott** [comment]
I investigated this issue before and it seems to be not directly EventGhost related. The way the process watcher plugin works, it enumerates the IDs of all running processes and then compares it with previously enumerated IDs. The enumeration on some setups can be CPU intensive, and as this is done up to 10 times per sec. (If I remember it correctly). There was forum topic about it, but the forum is currently down.. anyways, result of the topic was: one way to decrease CPU load is a higher delay between the enumeration in the plugin itself or to use the process monitor plugin to observe specific processes, which is much less CPU intensive.

**Comment by binarynoise** [comment]
Where do I get the process monitor plugin?
