### ISSUE TITLE
Interaction with buttons

### ISSUE THREAD

**Issue by Olit2000** [EventGhost/EventGhost#391]
It would be very nice to be able to interact with buttons on screen, like finding an clicking them
Use case: When some program starts (Task.Created) click on some buttons to do some init (like closing ads or ack warnings about something)

**Comment by kdschlosser** [comment]
you can "click" on specific buttons.

You need to use the find window action and target the specific button and after the find window action add the send keys action sending the {Return} keystroke to that button. it is the same thing as clicking on it.
the only times when this is not going to work is if the application has a custom drawn GUI. most browsers have a custom drawn GUI so you cannot target a button on say a webpage.

**Comment by Olit2000** [comment]
Would it be possible to move the mouse to a point relative to a container found be find window, e.g. from the top right corner 10px down and right, click there and then move the mouse back?

**Comment by DanEdens** [comment]
Yes I can help you with that this evening. I've already written the coordinate handler and return bit. Need to look at getting coords for location of found Window a bit I know we can.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kdschlosser** [comment]
have a look see at the task monitor plus plugin this will eliminate the need to use  Find Window, which is something i like to have users avoid using because of how long it takes to run..

you know when an application starts and stops and the payload is an object that has functions for controlling the application as well as collecting information. like size  and position.
the code would be simple...

event for the application starting
python command `eg.globals.my_application = eg.event.payload`

event for application terminating
python command `eg.globals.my_application = None`


The script below is the main script to carry out the mouse movements.. read the comments in the script. You will need to install the TaskMonitorPlus plugin for this to work. 

https://github.com/Boolean263/EventGhost-TaskMonitorPlus/tree/master/TaskMonitorPlus

you will need to create the 2 macros above. start and stop your application after you have the plugin installed.. you will see the events... drag and drop the events into the macros..

then create another macro. add the event that is supposed to cause the mouse to move.. paste in the code below into a python script action.. again read the script there are instructions in it. and it is also going to give you a better understanding on what is taking place inside of the script.

```python 
if not hasattr(eg.globals, 'my_application'):

    # now this is a crazy bit of code. the only time when eg.globals.my_application
    # is not going to exist is because EG was just started and no task monitor plus event has
    # has occurred letting us know the application is running. 
    # this is the only time we will use the Find Window action for this..
    # because our script relies on an object that is attached to an event as a payload
    #  we need to cause this event to occur..,.
    # because EG only processes one event at a time so long as this script is running the 
    # event is never going to be produced.. so how do we do that. well it's simple
    # we cause the other event to occur. it is going to get queued. then we create another 
    # event and pass this events parameters to it.. in effect duplicating the event. 
    # that event is going to get queued after the other one... we then tell the macro to stop running
    # and exit the script. This will allow the first event to run populating eg.globals.my_application
    # with the needed object.. then our duplicate event is going to run which will bring us back 
    # into this script except the script is going to know the application is running.   
    # Then we are able to access the object we need. pretty creative huh??
    eg.globals.my_application = None
    del eg.lastFoundWindows[:]
    # copy the find window action as Python and paste it here
    if eg.lastFoundWindows:
        hwnd = eg.lastFoundWindows[0]
        eg.plugins.TaskMonitorPlus.info.plugin.CheckWindow(hwnd)

        eg.TriggerEvent(
            prefix=eg.event.prefix,
            suffix=eg.event.suffix,
            payload=eg.event.payload, 
            source=eg.event.source
        )

# if the application is not running stop the running of the macro and exit the script.
if eg.globals.my_application is None:
    eg.StopMacro()
    eg.Exit()
  

app = eg.globals.my_application

# here is a list of available functions that can be used to control the application
# app.pid
# app.name
# app.title
# app.window_class
# app.IsAlive()
# app.IsActive()
# app.Animate(slide, blend, direction, show, hide, duration)
# app.SendKeystrokes(text, useAlternateMethod, mode)
# app.Flash(caption, tray, until_active, continuous, times, speed)
# app.BringToTop()
# app.IsVisible()
# app.EnableKeyboardMouse(enable)
# app.IsKeyboardMouseEnabled()
# app.Restore()
# app.Minimize(activate, force)
# app.Maximize()
# app.SetPosition(x, y)
# app.SetSize(width, height)
# width, height = app.GetSize()
# x, y = app.GetPosition()
# app.Show(flag, activate, default)
# app.Hide()
# app.Destroy()
# app.Close()
# app.SendMessage(message, wparam, lparam)
# app.PostMessage(message, wparam, lparam)
# app.GetParent()
# app.Focus()
# app.HasFocus()

# check if the window is visible. is it is not then make it visible
if not app.IsVisible():
    app.Restore()

# this will bring the application to the forgeround so the mouse can interact with it.
app.BringToTop()

# this will always return the top left corner of the window.
# so if you know where whatever it is you want to move the mouse to figure out where the x, y is 
# relative to the upper left corner.
# if it's a button and it is 150 pixels down and 300 pixels right from that upper left corner 

x, y = app.GetPosition()
# you should always be adding to the position of the window. always..
x += 150
y += 300

# set the mouse to the new position
from eg.WinApi.Dynamic import SetCursorPos
SetCursorPos(x, y)

# set this so if there are any actions to perform after this script that are 
# going to interact with the application they will be able to do so.
eg.lastFoundWindows = [app.hwnd ]
```

**Comment by kdschlosser** [comment]
That script will get the application position. move the mouse relitive to the upper left corner of the app. wait until the mouse has moved there.. press the left mouse button down. wait 100 milliseconds release the left button wait another 100 milliseconds and then move the mouse back to where it started from.

**Comment by binarynoise** [comment]
I can't download the plugin beacause the forum attachment could not be found. 
How can I manually create/build the .egplugin file (which seems like it's only a zip with special name)

**Comment by kdschlosser** [comment]
you can download the plugin from the github repo link I provided.. Open the zipfile that you download.. in that zipfile will be a folder name that ends in master.. go into that folder and extract the folder TaskMonitorPlus to `c:\programdata\eventghost\plugins`

then add the plugin.. I do not believe you need to shutdown EG to do this.. I can't remember to be honest.. You will know  if you added it to the above folder and it is not showing up in your available plugins list... you will need to restart EG.

**Comment by Olit2000** [comment]
That worked, and yes, you dont need to restart EG. 
Unfortunately I don't need this anymore. 
Thanks for your help anyway, and it hopefully will help someone else (or me in the future).
One thing though: I think it would be nice, if you mapped the python commands to EG-commands for the non-programmers.
Another thing I find weird is that you need the Task Monitor plugin enabled to make the TMPlus plugin work. All the events are duplicated then (one from TM and one from TMP)
And sorry that I commented last time with the wrong account :wink:

**Comment by kdschlosser** [comment]
they both use some of the same backend. If you remove both of the plugins and then restart EG and only install the task monitor plus plug it will work on it's own.
