### ISSUE TITLE
http://www.eventghost.net/ down?

### ISSUE THREAD

**Issue by jonisb** [EventGhost/EventGhost#393]
I'm getting a "generic" page on http://www.eventghost.net/ whats going on?

It shows this message at the bottom:
"This domain is pending renewal or has expired. Please contact the domain provider with questions."

**Comment by kdschlosser** [comment]
Yeah apparently it is down. Never got a renewal e-mail from the registar for the domain.

So now I am trying to renew it and their cart doesn't load for me to pay for it.. so now I am in a chat with them. Hopefully they will be able to repair the thing kind of fast. I am not able to get to the checkout using Chrome, IE or Firefox. I wonder if I should try Safari

**Comment by jonisb** [comment]
Nice, looks like its working.
