### ISSUE TITLE
Website has incorrect download link

### ISSUE THREAD

**Issue by shiukaheng** [EventGhost/EventGhost#394]
"Download For Free Now" on eventghost.net directs to https://tympanus.net/codrops/2015/03/12/freebie-forkio-one-page-website-template/ instead of installer.

**Comment by DanEdens** [comment]
It works correctly for me now. 
Where you able to get it downloaded?

**Comment by kdschlosser** [comment]
I fixed it. Sorry I forgot to mention that. TY @shiukaheng for reporting the problem.
