### ISSUE TITLE
Have all repo maintainers abandoned the project?

### ISSUE THREAD

**Issue by dequi** [EventGhost/EventGhost#396]
@topic2k, @CarsonF, it has been over a year since there were any updates to the repo, have all maintainers abandoned the project and forgot to leave someone else in charge? Updates to plugins have been posted to the forum instead, what defeats the purpose of the repo.

**Comment by CarsonF** [comment]
This project has struggled with maintainers for the past decade. I can really only take credit for the move from svn to git. I was hoping that with the move it would become more visible for other and easier for others to make contributions. I wanted to do more, but found that [home-assistant.io](https://www.home-assistant.io/) fit my needs way better and is actively developed.
In the past I was happy to give anyone write access just to keep the move to GitHub from failing. Now that there have been devs here I would rather them speak up since this isn't really my project.

**Comment by kdschlosser** [comment]
I have not abandoned it.  Actually I would like to have ownership rights to the repo. I do not know what happened to @topic2k I have tried to message him on slack chat and I have sent him PM's on the forum as well. I have not gotten an answer at all.

**Comment by CarsonF** [comment]
Sorry @kdschlosser, I'm terrible with email. I'm great with GitHub notifications though lol...
I just re-sent the invite to the org

**Comment by kdschlosser** [comment]
@CarsonF I have not gotten the invite.

I did not know you changed to using HA, so I thought you were still popping into the forum. I have wanted to keep on moving forward with this but @topic2k vanished. He said to me that he needed some time off. I didn't think he was going to be gone for over a year. I have been wanting to continue development of EG but without a way to get the PR's merged there was no point in even creating them. I was going to create another repository and work from that. Which is something I did not want to do.

There are a couple of bugs that have been fixed and I will get them added to EG. then I am going to release version 0.5. then onto 1.0 and the change to python 3.7 or possibly 3.8. I have not yet decided if i am going to remove stackless. I might.

**Comment by kdschlosser** [comment]
never mind. The invite only shows up in an e-mail. Kind of dumb in GitHubs part

**Comment by CarsonF** [comment]
Hmm ok I canceled the pending one and sent another.

I didn't realize no one had access to merge PRs 😞 

Cool, love the ambition!

**Comment by dequi** [comment]
@CarsonF  >  I'm terrible with email. I'm great with GitHub notifications though lol...

I remembered this from the last time the repo was "dead" I think it was in 2016. I Was sure you would see the mention.

@kdschlosser I think the issue can be marked as solved now?

**Comment by kdschlosser** [comment]
That it is...
