### ISSUE TITLE
Eventghost forum activation

### ISSUE THREAD

**Issue by nairnmonster** [EventGhost/EventGhost#405]
Hi there,

I've tried my best to find a solution in the forum or on here but I'm at a loss.

I cannot get an activation email from http://www.eventghost.net/

I'm sorry if I'm posting in the wrong please but any help would be amazing.

Many thanks

**Comment by kdschlosser** [comment]
whats you username on the forum?

**Comment by nairnmonster** [comment]
Hey,

it's: nairnmonster

Thanks

**Comment by kdschlosser** [comment]
ok you should not be activated. so try and login

**Comment by nairnmonster** [comment]
I'm in, thanks so much for that. Very much appreciated!!!

**Comment by kdschlosser** [comment]
no worries m8
