### ISSUE TITLE
Opening Options fails with locale error

### ISSUE THREAD

**Issue by hugalafutro** [EventGhost/EventGhost#407]
**Describe the bug**
Upon clicking File / Options an error is produced and the options window doesn't appear

**To Reproduce**
Click File
Click Options

**Expected behavior**
Options window appearing

**Additional context**
Traceback (most recent call last) (0.5.0-rc6):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\OptionsDialog.py", line 194, in Configure
    languageChoice.SetSelection(languageList.index(config.language))
ValueError: 'en_US' is not in list

**EventGhost version**
Software
Program Version: 0.5.0-rc6
Build Time: Mon, 24 Dec 2018 09:01:48
Python Version: Stackless Python 2.7.12 final 0
wxPython Version: 3.0.2.0

System
Operating System: Microsoft Windows 10 Professional, 64-bit (build 19041)
CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
RAM: 32.0 GB

USB-Devices
Xbox 360 Wireless Receiver for Windows: USB\VID_045E&PID_0719
Generic Bluetooth Radio: USB\VID_0A12&PID_0001
Generic USB Hub: USB\VID_1A40&PID_0101
USB Composite Device: USB\VID_1E7D&PID_2E7C
USB Input Device: USB\VID_1E7D&PID_2E7C&MI_00
USB Input Device: USB\VID_1E7D&PID_2E7C&MI_01
USB Composite Device: USB\VID_1E7D&PID_3098
USB Input Device: USB\VID_1E7D&PID_3098&MI_00
USB Input Device: USB\VID_1E7D&PID_3098&MI_01
USB Input Device: USB\VID_1E7D&PID_3098&MI_02
USB Input Device: USB\VID_1E7D&PID_3098&MI_03

**Comment by kdschlosser** [comment]
has already been fixed!.
