### ISSUE TITLE
Is there a binary only release?

### ISSUE THREAD

**Issue by deostroll** [EventGhost/EventGhost#412]
Is there a binary only release? Looking to get this software working right away from the command line and manually, and, not as a windows service.

**Comment by DanEdens** [comment]
You can set it up in your IDE via this post, and build it as binary from there.
http://www.eventghost.net/forum/viewtopic.php?f=10&t=10480
EG doesn't run as a service currently.
It can, but doesn't by default and is generally not encouraged.

**Comment by kdschlosser** [comment]
@deostroll 
You can download a binary release from https://github.com/EventGhost/EventGhost/releases/tag/v0.5.0-rc6

**Comment by dequi** [comment]
This issue is closed because it has had no response from the OP for more than 60 days after a possible solution has been offered.
