### ISSUE TITLE
Non-Profit Status...Application in Canada 

### ISSUE THREAD

**Issue by Soupy51** [EventGhost/EventGhost#421]
Ok.  What will Website be? 

.org I would assume?  www.eventghost.org.  Who is active currently has access to Forum details, current website ownership and transfer rights?

My suggestion is to differentiate from previous websites...i.e. "Under New Management"

First things first...Is anybody against listing a canadian non-profit?  No receipts for any donations.  Can still donate to indy plugin developers, buy a coffee and such. All other business development is conducted by committee.

I want to see a show of hands.  

My personal email!- steve@rpad.ca  I have the means and know-how to push forward with this, but need whomever currently has the permissions et al, to make the commitment for several months until such time as volunteer personnel are slotted into community agreed upon positions.  I would need time to further develop the non-profit process as well as develop the legal ramifications/obstacles/cost.

I am interested in developing EG into a Python 64 bit, 3.10.8 version product.  Which would require a long-term commitment by all involved.  Let's sell the idea of a non-clouded, but up to date application that is not relying upon a single person.

Using community-driven marketketing, management, engineering and programming skills to very, very slowly drag this application, kicking and screaming into the 21st century.

Talk to me please?

**Comment by DanEdens** [comment]
@Soupy51 Are you interested in helping me convert Eventghost to Mojo? I am going to start work once the windows binary is released. 
https://github.com/DanEdens/EventGhost-Mojo

**Comment by Soupy51** [comment]
Let me read up on mojo and get back to you.  I have started down the road
of Node-Red looking for a web based replacement of eg.
Give me a week or so and I will reply back.  Any fast overview websites to
get me going quick?

S

**Comment by Soupy51** [comment]
Dan, Am interested in the management of the open source idea but am not a
programmer. I was a college student 30 yrs ago and learned c++, c several
extinct languages called COBAL and Fortran.  Made money from Y2K. Spent
last 30 years managing construction sites as a project manager. If MOJO
makes the jump to windows in a 64bit version then show me what is possible
and we can talk further.  I'm in Toronto Canada, where's home for you?
Oh, retired due to injury at 57, looking for some work to keep me busy.
From your perspective as a developer what are the big picture pros and cons
of jumping over other than the claimed speed increase and python continuity?

**Comment by DanEdens** [comment]
I got started as a construction Site project manager too! I was a geotechnical sensors technician. 
Im in New England in the US. 😄 
Yes that is the idea, to get it off of the older dependencies and into both new python and 64bit. 

The starting place for this project is the Stopped work Kevin did for x64. Both are major goals, that I'm not entirely sure yet how work to each end will shape up. 

I will start replacing the internal python with mojo, since it will be able to handle the things py3 prevented, such as multithreading.
