### ISSUE TITLE
EventGhost hangs after selecting Pulse-Eight CEC plugin

### ISSUE THREAD

**Issue by LegzRwheelz** [EventGhost/EventGhost#428]
I am uncertain if this is a plugin or EG error, I apologize if I posted incorrectly

**Describe the bug**

Installing the Pulse Eight CEC plugin works flawlessly, however after attempting to add it to the tree, EG hangs indefinitely.

**To Reproduce**

1. Install the Pulse Eight plugin
2. Right-Click on Autostart
4. Select "Add Plugin..."
5. Select Pulse Eight CEC plugin
6. EG hangs

**Expected behavior**

To add the plugin to the tree for configuration. I do not know what is supposed to happen next as I haven't made it this far.

**Additional context**

Windows 11 pro, first time using the Pulse Eight device, EG and the plugin. 
Additionally, I noticed that when I alt+tab out of EG, the window preview shows the device's plugin information in the right hand pane (see screenshots)

This is how it looks normally

![image](https://github.com/user-attachments/assets/fbc34199-d7d3-4db9-8fd8-74d5c5ae8a0a)

This is the preview I am talking about when I alt+tab out of the window.

![image](https://github.com/user-attachments/assets/80615b34-e895-4795-a201-c8f78da5f074)

EDIT: Now when I open EG, I get the following error

![Screenshot 2024-11-09 202053](https://github.com/user-attachments/assets/0a52fba1-4b1f-439e-994c-04e0d4b11a4f)

and the log looks like this:
```text
Traceback (most recent call last):
  File "EventGhost.pyw", line 51, in <module>
    import __main__
  File "C:\Program Files (x86)\EventGhost\eg\__init__.py", line 31, in <module>
    import Cli
  File "C:\Program Files (x86)\EventGhost\eg\Cli.py", line 30, in <module>
    import PythonPaths
  File "C:\Program Files (x86)\EventGhost\eg\PythonPaths.py", line 23, in <module>
    import winreg
```

**EventGhost version**

```text
Software
Program Version: 0.4.1.r1722
Build Time: Wed, 03 Feb 2016 08:20:52
Python Version: Stackless Python 2.6.5 final 0
wxPython Version: 2.8.12.1

System
Operating System: Microsoft Windows Unknown OS 6.2 Professional, 64-bit (build 9200)
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
RAM: 32705 MB

USB-Devices
USB Attached SCSI (UAS) Mass Storage Device: USB\VID_0411&PID_031B
Xbox Wireless Adapter for Windows: USB\VID_045E&PID_02FE
USB Composite Device: USB\VID_046D&PID_C534
USB Input Device: USB\VID_046D&PID_C534&MI_00
USB Input Device: USB\VID_046D&PID_C534&MI_01
Generic USB Hub: USB\VID_046D&PID_CA83
<unknown name>: USB\VID_046D&PID_CA84
Generic USB Hub: USB\VID_05E3&PID_0608
Generic USB Hub: USB\VID_05E3&PID_0610
Generic SuperSpeed USB Hub: USB\VID_05E3&PID_0626
Generic Bluetooth Radio: USB\VID_0A12&PID_0001
USB Attached SCSI (UAS) Mass Storage Device: USB\VID_0BC2&PID_AB38
Generic USB Hub: USB\VID_0BC2&PID_AB44
Generic SuperSpeed USB Hub: USB\VID_0BC2&PID_AB45
USB Mass Storage Device: USB\VID_174C&PID_7720
eHome Infrared Receiver (USBCIR): USB\VID_1934&PID_5168
Generic USB Hub: USB\VID_1A40&PID_0101
Generic SuperSpeed USB Hub: USB\VID_2109&PID_0812
Generic SuperSpeed USB Hub: USB\VID_2109&PID_0813
Generic SuperSpeed USB Hub: USB\VID_2109&PID_0815
Generic SuperSpeed USB Hub: USB\VID_2109&PID_0817
Generic USB Hub: USB\VID_2109&PID_2812
Generic USB Hub: USB\VID_2109&PID_2813
Generic USB Hub: USB\VID_2109&PID_2815
Generic USB Hub: USB\VID_2109&PID_2817
USB Composite Device: USB\VID_2548&PID_1002
Pulse-Eight USB to HDMI CEC Adapter (rev.2): USB\VID_2548&PID_1002&MI_00
USB Input Device: USB\VID_2548&PID_1002&MI_02
USB Composite Device: USB\VID_28DE&PID_1142
USB Input Device: USB\VID_28DE&PID_1142&MI_00
USB Input Device: USB\VID_28DE&PID_1142&MI_01
USB Input Device: USB\VID_28DE&PID_1142&MI_02
USB Input Device: USB\VID_28DE&PID_1142&MI_03
USB Input Device: USB\VID_28DE&PID_1142&MI_04
```

**Comment by MP-Munich** [comment]
Hello LegzRwheelz,

this issue is not on EventGhost-side. The Pulse Eight plugin is faulty.
This issue was reported one year ago by multiple users:
https://github.com/Pulse-Eight/libcec/issues/643
https://support.pulse-eight.com/support/tickets/39771

Feel free to add your comment to these posts. 😊
