### ISSUE TITLE
Upgrade to Python 2.7

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#5]
I'd like to see the first Git release of EventGhost, v0.5.0, include Python 2.7. When #2 is complete, we'll begin investigating this possibility.

**Comment by topic2k** [comment]
https://github.com/topic2k/EventGhost/tree/python27
The above runs on Python 2.7.9 Stackless. The .pyd and .dll in lib27/site-packages i patched with a hex editor to use python27.dll . Don't know if it's enough. At least it starts but i haven't tested any plugins etc.
