### ISSUE TITLE
Deleting an item in the configuration tree scrolls the view

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#53]
I'm currently taking inventory of what else we need to do before releasing the beta, and this regression came to mind. It's related to #35 and has been bothering me since we accepted that PR, but I keep forgetting to report it.

To reproduce, simply delete any item in your tree. The view will scroll to just below the root of the deleted item. This shouldn't happen.

Since you're the `wxPython` expert, @topic2k, I'm leaving this one to you. I'm betting you already know exactly where to begin looking.

**Comment by topic2k** [comment]
thx :) , but i'm really no expert and i must say that i not fully know what you mean. Can you give an example, maybe screenshots?

**Comment by blackwind** [comment]
Well, you are in comparison to Pako and I. Aside from Bitmonster, I think you're the only one who's done any meaningful work on the `wxPython` code.

We start with this:

![](http://i.imgur.com/saSkQnq.png)

When the item is deleted, this happens:

![](http://i.imgur.com/BySfmsT.png)

But the view should remain where it was, like this:

![](http://i.imgur.com/5YpPNig.png)

It looks like the deleted item has to be in a folder for this to occur. Deleting a macro from the root of the tree appears to work properly.

**Comment by topic2k** [comment]
@blackwind : please, in `eg.Classes.MainFrame.TreeCtrl` replace lines 797-800

    self.Freeze()
    self.SelectItem(self.visibleNodes[self.root])
    self.SelectItem(self.visibleNodes[parent])
    self.Thaw()

with

     self.UnselectAll()

and try if that change will fix it.

**Comment by blackwind** [comment]
Well, it works in the sense that it corrects the problem, but in terms of usability, it'll make deleting a bunch of items with the keyboard a headache, as you'll have to keep scrolling back down from the top.

I took a look at how this was handled prior to #35, and apparently neither the replaced block nor the replacement are there, and it just works. If I remove both now, though, when you try to delete two items in a row without moving the selection, `wxPython` 3 gives us this traceback:

```
Traceback (most recent call last) (WIP):
  File "[...]\eg\Classes\MainFrame\__init__.py", line 211, in OnDelKey
    self.DispatchCommand('OnCmdDelete')
  File "[...]\eg\Classes\MainFrame\__init__.py", line 505, in DispatchCommand
    getattr(self.document, command[2:])()
  File "[...]\eg\Classes\Document.py", line 205, in CmdDelete
    eg.UndoHandler.Clear(self).Do(self.selection)
  File "[...]\eg\Classes\UndoHandler\Clear.py", line 32, in Do
    self.treePosition = eg.TreePosition(item)
  File "[...]\eg\Classes\TreePosition.py", line 31, in __init__
    self.path = item.GetPath()
  File "[...]\eg\Classes\TreeItem.py", line 272, in GetPath
    path.append(parent.childs.index(item))
AttributeError: 'NoneType' object has no attribute 'childs'
```

It seems an item needs to be explicitly selected after a deletion to avoid that, which, I guess, is why [you added lines 797-800](https://github.com/EventGhost/EventGhost/commit/c37409753ff2d66c445e7922d18f84dd73b2fd50) in the first place. To get us back to the original behavior, is there a way to explicitly select the next item down in the tree without scrolling?

**Comment by blackwind** [comment]
Got it. If you don't freeze, it doesn't scroll.
