### ISSUE TITLE
Provide 64-bit builds of EventGhost

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#58]
At this time, I see no good reason whatsoever to roll 64-bit builds of EventGhost alongside our existing 32-bit builds, as it'll only make our lives more difficult as developers, fragment the userbase, and provide no tangible benefit to anyone. Eventually, though, someone, somewhere is going to post why they absolutely must have a 64-bit build. Let's keep that discussion in this issue. Should the community come up with enough valid(!) reasons to do this, we'll take a closer look at it.

**Comment by kdschlosser** [comment]
I do have to agree with you on that. after reading about the benefits of conversion unless there is heavy math involved in the application the only thing it will do is cause EventGhost to use more memory. and not give any kind of a performance gain. It is just not worth either having to maintain a whole second set of code or congest a single version with both sets of code.

**Comment by kdschlosser** [comment]
I changed my view on this now that I have successfully built 64 bit versions of EG running Python 2.7 and 3.5

There was some issues that were difficult to track down. but I managed to get them sorted out.
