### ISSUE TITLE
Attach GUID to tree nodes so they can be programmatically accessed

### ISSUE THREAD

**Issue by blackwind** [EventGhost/EventGhost#70]
Actions that act on other nodes in the tree reference those nodes using `XmlIdLink()` -- for example, `eg.plugins.EventGhost.GetItemState(XmlIdLink(17))` -- so these actions fail when executed via Python Script or Python Command because `XmlIdLink()` isn't a built-in function. To make them work when called programmatically, we'll need to attach a unique ID (GUID) to each node.

**Comment by kdschlosser** [comment]
I have added this Enhancement to EventGhost don't know if you are interested

**Comment by blackwind** [comment]
As long as it's not going to be a continuous headache, the code is tight, and `CONTRIBUTING.md` has been followed, you have my attention. Like I said, nothing personal.

**Comment by kdschlosser** [comment]
i am going to be putting up a version of EG in my fork. you can take a look at it if you want,

**Comment by topic2k** [comment]
close by #133
