### ISSUE TITLE
Problem with `wxFlexGridSizer::AddGrowableCol()`

### ISSUE THREAD

**Issue by krambriw** [EventGhost/EventGhost#73]
Several plugins are now facing a problem with the wxFlexGridSizer::AddGrowableCol().
As  example, this one below (NMAP plugin). I also had a problem in my own MQTT Client plugin.
My previous code was:
`       mySizer.AddGrowableCol(1)
        mySizer.AddGrowableCol(2)
        mySizer.AddGrowableCol(3)
        mySizer.AddGrowableCol(4)
        mySizer.AddGrowableCol(5)
        mySizer.AddGrowableCol(6)
`
The new code is
`       mySizer.AddGrowableCol(0)
        mySizer.AddGrowableCol(1)
        mySizer.AddGrowableCol(2)
        mySizer.AddGrowableCol(3)
        mySizer.AddGrowableCol(4)
`
I also had to move the code "further down". It seems that it is more sensitive to index and actual number of columns initiated (it is correct that I have only 5 columns and the starting index should be 0)

Best regards, Walter (krambriw)

11:27:43   Traceback (most recent call last) (0.5.0-beta1):
11:27:43     File "C:\Program Files (x86)\EventGhost\plugins\Nmap\__init__.py", line 282, in Create
11:27:43       self.itemHeight = self.lb.GetItemHeight()
11:27:43   AttributeError: 'CheckListBox' object has no attribute 'GetItemHeight'
11:27:43   Traceback (most recent call last) (0.5.0-beta1):
11:27:43     File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
11:27:43       self.Configure(*args, **kwargs)
11:27:43     File "C:\Program Files (x86)\EventGhost\eg\Classes\ConfigDialog.py", line 106, in Configure
11:27:43       treeItem.Configure(*args)
11:27:43     File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionItem.py", line 80, in Configure
11:27:43       return self.executable.Configure(*args)
11:27:43     File "C:\Program Files (x86)\EventGhost\plugins\Nmap\__init__.py", line 2178, in Configure
11:27:43       Sizer.AddGrowableCol(1)
11:27:43     File "wx\_core.pyc", line 15368, in AddGrowableCol
11:27:43   PyAssertionError: C++ assertion "!m_cols || idx < (size_t)m_cols" failed at ..\..\src\common\sizer.cpp(1980) in wxFlexGridSizer::AddGrowableCol(): invalid column index

**Comment by blackwind** [comment]
This is a known side effect of #35 and not actually a bug. @topic2k has updated all the plugins we bundle; all other plugins will need to be updated by their authors. Ping @topic2k in #35 if you need assistance with this or anything else caused by the `wxPython` upgrade.

**Comment by krambriw** [comment]
Alright, clear as water ;)
Thanks

**Comment by blackwind** [comment]
Reopening this for a few days just so it's the first thing everyone sees when they come to post the same issue.
