### ISSUE TITLE
Modules I use in `site-packages` are missing

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#75]
There seem to be a lot of site-packages missing in the new version.
I use psutil and paramiko for example.

**Comment by topic2k** [comment]
None of the core functions or plugins use those packages. That's why they are missing. If you want to use them, you have to put them for example into the directory of the plugin using it or into `..\EventGhost\lib27\site-packages`.

**Comment by topic2k** [comment]
It looks like there are issues with timezones and/or dst.

**Comment by blackwind** [comment]
> None of the core functions or plugins use those packages. That's why they are missing.

Yep. Specifically, they were removed because of #20. You no longer have to petition Pako to include modules you want to use -- just [install Python 2.7](https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi) (x86 version, as it has to match EventGhost), run `pip install paramiko psutil`, and EventGhost will pick them up.

**Comment by ThomasBott** [comment]
hmm, I see, I must have missed that.
When I put something in site-packages, will it be removed with an update of eventghost or will it stay there?

Also: I can't get paramiko to work with this verison of EG:
```
import paramiko
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\Lib\site-packages\paramiko\__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Python27\Lib\site-packages\paramiko\transport.py", line 32, in <module>
    from cryptography.hazmat.backends import default_backend
  File "C:\Python27\Lib\site-packages\cryptography\hazmat\backends\__init__.py", line 7, in <module>
    import pkg_resources
  File "pkg_resources\__init__.pyc", line 68, in <module>
    t  File "pkg_resources\extern\__init__.pyc", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```
in python 2.7 natively it works just fine, any idea?

**Comment by blackwind** [comment]
Incidentally, the commit for #81 fixes this as well, as we now bundle the full version of `pkg_resources`. Try beta2 when I release it later tonight. I'm able to successfully `import paramiko` now in my dev build.

> When I put something in site-packages, will it be removed with an update of eventghost or will it stay there?

It'll stay there, but I recommend you use `%PYTHONPATH%` instead. When we upgrade to a different version of Python, the `lib27` folder will no longer be loaded.

**Comment by blackwind** [comment]
Just waiting for @kdschlosser's feedback on a few issues now. If his bug reports turn out to be legitimate, I'd like to get fixes for those into beta2 as well. Current ETA is tomorrow.

**Comment by ThomasBott** [comment]
> It'll stay there, but I recommend you use %PYTHONPATH% instead. When we upgrade to a different version of Python, the lib27 folder will no longer be loaded.

While this is a valid solution if you just work on your system, it's not that easy if you like to sahre your plugins and scripts with others.
I understand why the site-packages have been removed, but I have to say it's a little inconvinient for me.
As the libs were part of the EG default, I was relying on them in many scripts and plugins. OK, for plugins I can ship those libs with the plugins, but if you like to share scripts, the site-packages seem like the only possible option (I do like the new feature but I don’t want to explain anyone how to install python and then install the lib from the repository just to run a script)
It's still not a very good one, as you mentioned, but everything else is too complex.
That's also why I avoid using any lib that's not part of the default - but they were (even though core plugins didn't use them)

> Incidentally, the commit for #81 fixes this as well, as we now bundle the full version of pkg_resources. Try beta2 when I release it later tonight. I'm able to successfully import paramiko now in my dev build.

Cool, I'll check it out later this day, after it has been released!
