### ISSUE TITLE
Version Check is broken

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#77]
Upon installing the new Version it tells me there is a newer version available. I visit the page download the copy from there and install it. and Upon installing that version it does the version check yet again. and tells me a newer version is available.

looking at the version numbers in the dialog it seems as though there is a v before the one it is telling me is newer.

I have included a screen shot of the dialog

![newer version](https://cloud.githubusercontent.com/assets/10932297/17643868/a19538e6-6133-11e6-9d7d-d185842f62fe.jpg)

**Comment by topic2k** [comment]
Same issue as #75.

**Comment by kdschlosser** [comment]
Sorry about that I skimmed the other and thought it was something about the timezones and the version check. Thought it was a different issue
