### ISSUE TITLE
Automatically close and restart EventGhost on upgrade

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#78]
This is a suggestion not a bug. But having a button that will save EG and close it from the upgrade. And because it knows it was running to just start it again without asking.

**Comment by blackwind** [comment]
I'm not sure this is possible with Inno Setup, but I'll leave the issue open until someone investigates.

**Comment by blackwind** [comment]
I took a shot at this the other day in #103, but:

* Our Task plugin binds to the setup window, making the installer suggest closing itself as well. Obviously, this isn't possible. Probably fixable, but...
* We now uninstall the previous version before install, and Inno's uninstaller doesn't yet support restart handlers. Nothing I can do about this one.

If I spot a fix for the latter issue in a future Inno changelog, I'll take another look; in the meantime, closing this issue as impossible.
