### ISSUE TITLE
Implicit wildcard events not being processed

### ISSUE THREAD

**Issue by igvk** [EventGhost/EventGhost#80]
In the latest version of EG 0.5.0-beta1 the following stopped working:
When configured event name is simple (doesn't contain a dot), e.g. 'Play', and plugin generates event 'Plugin.Button.Play' - there is no match and the action doesn't fire.
Previously the action associated with the event name 'Play' was fired successfully.

**Comment by topic2k** [comment]
Can you give a more precise example? If i generate a event `Plugin.Button.Play` the macro with the associated event `Play` will be executed.

![play-event](https://cloud.githubusercontent.com/assets/6463113/17644542/e50ac9b4-6189-11e6-9504-bb4d868c8edb.png)

**Comment by igvk** [comment]
While in all previous version it worked, the latest version simply ignores the event.
The actual names of events in my config work the following way in the previous version:
    X10Mouse.Button.Play
       Play
          Zoom Player: Play
But in the latest version I see only:
    X10Mouse.Button.Play

**Comment by blackwind** [comment]
If I'm understanding you correctly, use "*.Play" as your event. The spaghetti code that used to be in the event handler may have accepted what you're doing, but we now require you make it explicit.

**Comment by blackwind** [comment]
I strongly question whether or not this "feature" was even intentional. I'd prefer to keep things the way they are, but I'll tell you what -- I'll leave this bug open for a few weeks. If we get enough complaints, I'll re-evaluate. Just know that it'll come at the cost of more CPU usage.
