### ISSUE TITLE
Plugins are executed at startup rather than install

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#84]
I have a plugin that is in development, and has some errors. In past versions of EG if the plugin was not installed it would not try to read the plugin file. This version now runs the plugin file at each startup. Not sure if this is by design, so I figured I would let you know.

**Comment by blackwind** [comment]
Need more information. How did you come to the conclusion that this is happening?

**Comment by blackwind** [comment]
Try as I might, I can't reproduce this one either.

**Comment by kdschlosser** [comment]
OK make a plugin and put some invalid code in it. mine happens to be a bad import. and i know it's a bad import but the old version of EG wouldn't throw a traceback for something like that unless you actually installed the plugin. now it throws the traceback whether or not the plugin is installed. I didn't know if there was a new way that EG handled the importing of plugins. it seems as though they are all imported at startup instead of install

it could have been why EG would hang if you started the script with the debug option before. they may have been exception catching on startup without the -debug and that wasn't used with the -debug. and i know i saw that you had fixed that problem but i do not know if that fix was instituted in this beta

**Comment by blackwind** [comment]
> mine happens to be a bad import.

Yep, that did it. I tried a bunch of bad code in a test plugin without success earlier, but I can now reliably reproduce by importing an invalid module. Thing is, I just verified that v0.4.1 does exactly the same thing -- even without `-debug`. Not the greatest behavior in the world, but not a new issue, and certainly not one worth bothering with at this stage.

**Comment by kdschlosser** [comment]
No worries. I don't remember ever getting a traceback before but I wasnt running the latest version of EG either I think I was running the version before last.
