### ISSUE TITLE
`eg.app.Restart()` causes EventGhost to hang

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#85]
If you put you PC into standby while EG is running and you wake it up again, EG is dead (no GUI anymore). You can still see the process in the Task Manager but it consumes one whole CPU as if the process is in a loop.
I verified that this issue doesn't exist with 0.4.1 r1722.
(Only testet this on Windows 10)

EG 0.5.0 beta1

**Comment by ThomasBott** [comment]
Tried it without any plugins and it worked... So I guess one or more plugins are causing this.

**Comment by ThomasBott** [comment]
OK, I identified the issue: One of the plugin restarts EventGhost by executing eg.app.Restart(), but if there are still events in the queue, EventGhost hangs forever. It works with EventGhost 0.4.1 r1722.
Here is a little script to reproduce it:

```
from time import sleep

eg.TriggerEvent("sldkfj")
eg.TriggerEvent("sldkfdfgj")
sleep(3)
eg.app.Restart()
```

**Comment by blackwind** [comment]
Confirmed. Investigating.

**Comment by blackwind** [comment]
The good news is that my initial hunch was correct, and I've known for hours exactly what's triggering this; the bad news is, I have absolutely no idea what to do about it, as the offending code needs to remain in place.

**Comment by blackwind** [comment]
Got it. Such an easy fix in hindsight.
