### ISSUE TITLE
Upgrade to the latest wxPython

### ISSUE THREAD

**Issue by topic2k** [EventGhost/EventGhost#9]
If a version of wxPython > v2.8 is the default version, the main frame of EG is shown, but then the app hangs.

**Comment by blackwind** [comment]
I spent a few hours checking into this last night, and the weird thing about it is that nothing in their [v2.9 migration guide](http://wxpython.org/migrationguide.php) seems to apply to us. I managed to get the main window responding, but literally NOTHING works besides scrolling and opening menus. Doesn't make sense.

**Comment by topic2k** [comment]
> If a version of wxPython > v2.8 is the default version, the main frame of EG is shown, but then the app hangs.

The Logcontrol get constantly a `EVT_SIZE` event. Commenting out the line `self.logCtrl.Bind(wx.EVT_SIZE, self.onLogCtrlSize)` in `eg\Classes\MainFrame\__init__.py` removes the app hanging.
After that there are some other needed fixes. A few i already found are in my [wxPython 3.0.2](https://github.com/EventGhost/EventGhost/compare/master...topic2k:wxPython302) branch.

**Comment by blackwind** [comment]
Great work. Can't wait to see the final result.
