### ISSUE TITLE
Adding a plugin with invalid import call causes EventGhost to hang

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#90]
If I add a plugin with a invalid import call (e.g. I import a plugin that's not available) doesn't throw an error but causes EG to hang.
Actually, it doesn't need to be an import command, anything that would throw an error before the plugin initializes causes EG to hang.

0.5.0 beta2

**Comment by blackwind** [comment]
I tried exactly this a couple days ago in response to another bug report, and it gave me a traceback. Gonna need more information on this one.

**Comment by ThomasBott** [comment]
Try this version of the Winamp plugin:
[Winamp.zip](https://github.com/EventGhost/EventGhost/files/419679/Winamp.zip)

**Comment by blackwind** [comment]
Confirmed. This was an issue in v0.4.1 as well, but probably worth fixing since it's a hang. It won't be high priority and I won't be releasing another quick beta because of it, but it's on my radar.
