### ISSUE TITLE
Traceback on extending `eg` node in PyCrust

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#91]
When I extend the eg node in PyCrusts Namespace browser, I can see the following Traceback in the EG Log if I have a plugin in my configuration that comes with a library:

```
08:29:15   Traceback (most recent call last) (0.5.0-beta2):
08:29:15     File "wx\py\filling.pyc", line 81, in OnItemExpanding
08:29:15     File "wx\py\filling.pyc", line 158, in addChildren
08:29:15     File "wx\py\filling.pyc", line 109, in objHasChildren
08:29:15     File "wx\py\filling.pyc", line 127, in objGetChildren
08:29:15     File "wx\py\introspect.pyc", line 64, in getAttributeNames
08:29:15     File "wx\py\introspect.pyc", line 114, in getAllAttributeNames
08:29:15     File "C:\Program Files (x86)\EventGhost\eg\Classes\UndoHandler\__init__.py", line 23, in __getattr__
08:29:15       mod = __import__(name, MODULE_GLOBALS)
08:29:15   ImportError: No module named __dir__
```

Here is the code the plugin uses to import the library which is in a subfolder of the plugin folder (in this case it's paramiko):
```
import os
import sys
mod_pth = os.path.abspath(os.path.split(__file__)[0])
sys.path.append(mod_pth)
import paramiko
```

Do I maybe need to import the lib differently? If yes, how?

0.5.0 beta2

Thank you!

**Comment by blackwind** [comment]
Confirmed, though I have absolutely no idea what would've caused this. Again, not high priority, but it's now on my radar.

Great issue titles, by the way. I love not having to moderate.

**Comment by ThomasBott** [comment]
It's an annoying thing because the cursor changes to a hourglass when this happens, but besides this I didn't notice any issues, so I think it's not too urgent.

> Great issue titles, by the way. I love not having to moderate.

haha, you're welcome!

**Comment by topic2k** [comment]
I have a simple workaround for this, but i have not enough understanding of these EG functions and if it will break something other. [See here](https://github.com/topic2k/EventGhost/blob/wxPhoenix/eg/Classes/UndoHandler/__init__.py)
I simply check if the name given is `__dict__` and in that case return fake function to satisfy pyshell.

**Comment by blackwind** [comment]
Ah, so @ThomasBott = Sem;colon. Mystery solved!

A couple things about your plugin:

* Just `import paramiko`. EventGhost is smart enough to try importing from the plugin folder, and it was smart enough in v0.4.1 as well.
* `kind` should be "other". "External Equipment" (renamed to "Hardware Control" in v0.5.0-beta4) is for stuff like A/V receivers and smart home gadgets.

Regarding the proposed fix, I'm not going to pretend I know what the point of that function is either, but I've gone ahead and implemented the fix using `try`/`except` so that, if `__dir__` turns out to be valid for whatever reason, it's not skipped over.

**Comment by ThomasBott** [comment]
> Ah, so @ThomasBott = Sem;colon. Mystery solved!
Oh, no! He knows my secret!! ;-)

> Just  import paramiko . EventGhost is smart enough to try importing from the plugin folder, and it was smart enough in v0.4.1 as well.
Nope, not properly, I tried that. It may work for you because you installed paramiko and it's dependencies via pip.

>  kind  should be "other". "External Equipment" (renamed to "Hardware Control" in v0.5.0-beta4) is for stuff like A/V receivers and smart home gadgets.
I'd say that's a bit of a grey area, isn't it? You use SSH to control external devices, also in this category are things like xPL, which is similar, isn't it?
Anyway, I guess you're right and "other" makes more sense, I'll change that with the next release.

**Comment by blackwind** [comment]
> Nope, not properly, I tried that. It may work for you because you installed paramiko and it's dependencies via pip.

Move your `import`s above the `eg.RegisterPlugin()` call. Works for me without `paramiko` installed.

I strongly recommend using [`flake8`](https://flake8.readthedocs.io/) if your editor has a plugin for it. It would've told you to do that in the first place.

> I'd say that's a bit of a grey area, isn't it? You use SSH to control external devices, also in this category are things like xPL, which is similar, isn't it?

Technically, you use SSH to control an SSH server, which, depending on what you're connecting to and which commands you issue, may or may not control hardware.

**Comment by ThomasBott** [comment]
> Move your  import s above the  eg.RegisterPlugin()  call. Works for me without  paramiko  installed.

Ah, that's the trick! ^^ Thank you!
