### ISSUE TITLE
Lost data after re-upgrade from 0.4.1 to 0.5.0

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#93]
I have a critical one this time: After an upgrade from 0.4.1 to 0.5.0 I lost all my data in the config folder and in the user plugins folder!! (also everything that was in the EventGhost program dir, but that's not so important)
Luckily my weekly full backup ran yesterday, so I didn't loose any of my work, that would have been a nightmare! :)
So here is what I did:
I had 0.4.1 r1722 installed and upgraded to version 0.5.0 beta1.
I noticed that lots of plugins doesn't work with 0.5.0 in my current config, so I downgraded to 0.4.1 again. Today I upgaded again to version 0.5.0 beta2 and everything was gone, just the stuff that comes with EG was there, the installer removed everything that was there...
I think the problem only appears if you upgrade, downgrade and upgrade again.

**Comment by blackwind** [comment]
Did you uninstall v0.4.1 first, or did you install v0.5 on top of it? If it's the former, unfortunately, that's a known issue, and there's nothing I can do about it; if it's the latter, I have absolutely no idea why that would occur. Here's what's happening:

> Because the v0.4.1 installers remove that folder on uninstall, the new installer renames it to `EventGhost.bak`, uninstalls your previous version of EventGhost, and then renames back to `EventGhost`. We have to uninstall the previous version so Python 2.6 stuff doesn't get mixed in with the new stuff.

The original developers made the bone-headed design decision to remove ALL EventGhost data on uninstall, and the damage is already done -- people are running these versions in the wild, and when they're removed, this is what happens. I've attempted to work around the issue with the rename trick, but apparently [that's not working for everyone](https://github.com/EventGhost/EventGhost/issues/83), and it'll only work if you haven't uninstalled v0.4.1 on your own first.

**Comment by ThomasBott** [comment]
Of course I didn't uninstall any version, I always did in place upgrade/downgrads, that's why I posted it... And it happened to me on two PCs, both running Win10.
And I defiantly lost the data after installing 0.5.0 the 2nd time, not any other version. 

From your explaination I could imagine the issue is installing 0.4.1 over 0.5.0. Maybe the 0.4.1 installer doesn't install properly over 0.5.0 and then the 0.5.0 installer doesn't recognise the 0.4.1 installation properly and doesn't do the backup stuff (it did perform the uninstall though).

I like to point out that it would have been very painful to loose all my data this way, without any word of warning, VERY!
It's tricky, maybe you are carefull and think "ah, I'll backup my data before checking out 0.5.0" and all went well with the upgrade, then you downgrade because ... reasons and upgrade again later, but this time don't do a backup as it went well last time - and boom, all your data is lost.

**Comment by blackwind** [comment]
> Maybe the 0.4.1 installer doesn't install properly over 0.5.0 and then the 0.5.0 installer doesn't recognise the 0.4.1 installation properly and doesn't do the backup stuff (it did perform the uninstall though).

If it did the uninstall, it tried to do the rename. I guess the only explanation that remains is that another program (anti-virus or similar) prevented the rename operations. I'll see what I can do about making it retry indefinitely until it succeeds.

**Comment by ThomasBott** [comment]
Thx!
I agree it's a weird issue, but I believe it's reproducible.

**Comment by blackwind** [comment]
Try [this dev build](https://ci.appveyor.com/api/buildjobs/6bcexcaf2plid6xb/artifacts/_build%2Foutput%2FEventGhost_WIP-2016.08.17-02.08.24_Setup.exe). If you can reproduce with beta2 and can't with the dev build, I'll push it as beta3.

**Comment by ThomasBott** [comment]
Confirmed! Thx!
