### ISSUE TITLE
Setup is unable to backup user data

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#96]
When I try to update 0.5.0 beta2 to 0.5.0 beta3, I get this error:
![egsetup](https://cloud.githubusercontent.com/assets/1479181/17749736/5b9d35a2-64bf-11e6-8000-b792db285172.PNG)
Setup did rename the EventGhost folder in ProgramData to EventGhost.SetupBackup, but not the config folder (yet).
Any idea how to get arround this?

Using Windows 10

**Comment by blackwind** [comment]
Why, oh why, did they have to remove user data on uninstall? What a nightmare.

Well, the good news is that #95 is working as intended. If, after 20 tries, it was unable to rename your config folder, we should be able to rule out anti-virus. Either `EventGhost.SetupBackup` already exists or your permissions are fried. My best suggestion would be to create a new folder called `EventGhost`, copy the contents of the old folder into it, and try again. But then, you've already tried that, haven't you?

**Comment by ThomasBott** [comment]
I tried like 5 times in a row (I only renamed EventGhost.SetupBackup back again, didn't copy)
Anyway, the strange thing is, I just tried it again and it worked without an issue.
So, I can't reproduce it this time...
If it was an anti-virus software, it must have been Windows defender, I don't have any 3rd party anti-virus software installed.
Another thing I don't understand is: Why did it even create the SetupBackup when updating from 0.5.0 beta2 to beta3, I thought that only happens if you upgrade from 0.4 ?

**Comment by blackwind** [comment]
In short, I don't know Pascal (Inno Setup's scripting language) and wanted to do as little with it as possible. I'm sure it's possible to pull the original version number from somewhere, compare it, and do the backup/restore actions only when upgrading from < v0.5 -- the code for that just isn't in there at the moment.

Glad to hear you're up and running, at any rate. I'll take another look at the setup script in the coming days.

**Comment by kdschlosser** [comment]
I have a question on this. By chance would this not backing up of the config data folder cause a new config folder to be created with an empty tree and created a new config file? i know this dialog was just put in but but on the previous beta when the dialog wasn't there and the install process would continue

**Comment by blackwind** [comment]
I believe that to be the cause, yes.

**Comment by blackwind** [comment]
I've put a lot of work into the install script over the past few days and learned more Pascal than anyone should ever have to in 2016. Please do see if you can break [the latest dev build](https://ci.appveyor.com/api/buildjobs/mx5xk932iahhsk7f/artifacts/_build%2Foutput%2FEventGhost_WIP-2016.08.20-04.52.50_Setup.exe), upgrading to and downgrading from various versions, so we don't have to go through another round of this come the next beta.
