### ISSUE TITLE
Log doesn't scroll at certain window sizes

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#97]
I have tested this with Python script. and with a for loop on start of a plugin. but the log doesn't automatically scroll.

I know there were modifications to that portion of it. but is it not supposed to automatically scroll at all?? even when the slider is all the way at the bottom position?

**Comment by blackwind** [comment]
Again, unable to reproduce. Need more information.

**Comment by kdschlosser** [comment]
it just does not automatically scroll at all.

empty tree with just a python script in it running this code for example

`
for i in range(50):
    eg.PrintNotice(str(i))
`

or even eg.Print
or eg,TriggerEvent

nothing seems to make the log automatically scroll.

and this is a brand new clean install nothing changed or installed.

I don't know if it is supposed to automatically scroll at all. it used to and would stop if you click the scroll check box at the bottom. i thought the modifications that had been made to the scrolling would have the log automatically scroll if you had the slider all the way down. not sure what had been done to it.

and the last line of text  in the log if it is full is cut in half.

 IYE!
I was going to take a screen shot of the cut off text. And as soon as I closed the Python Script Editor it scrolled.

So that is what the problem is.

You have to close any open dialogs to have the log automatically scroll. Tho i am not sure if this is specific to just the python script editor.

but the log didn't scroll either when I used the broadcaster plugin and added the same fore loop to the start of the plugin. I did that for a test to see if it was specific to just the Script Editor.

**Comment by kdschlosser** [comment]
AHHH ok. i Nailed it down to exactly what it is.

make that Script and place it into the AutoStart tree item.

Then close EG and Restart it (after saving of course.)

then the automatic scrolling stops functioning all together

**Comment by blackwind** [comment]
Still can't reproduce with the editor open or with the restart trick.

**Comment by blackwind** [comment]
For what it's worth, I was never able to reproduce the problem you had with the "Scroll log" checkbox either. Never once in all my time with EventGhost have I ever been affected by either issue. When it's supposed to scroll, it scrolls; when it's not supposed to scroll, it doesn't.

My suspicion was that all the overriding of core functions you do in your plugins was the culprit, but if you've honestly and truly tested this in an empty config, I'm already out of ideas.

**Comment by blackwind** [comment]
Actually, I might be right after all. Turns out that when the program loads the list of plugins, it executes each plugin up to the `eg.RegisterPlugin()` call. If you have anything above that in any of your plugins, that code will be executed at startup whether the plugin is in your config or not. For example:

```
import eg
eg.AddPluginDialog = None
eg.RegisterPlugin(
  name = "Test Plugin"
)
```

Save that code as a plugin file, run EventGhost, and open the "Add Plugin..." dialog. EventGhost will crash because `eg.AddPluginDialog = None` has overridden it.

**Comment by kdschlosser** [comment]
I never had a problem with the Scroll Lock. i never even knew it was there until after I made the plugin. Someone else had stated that it didn't function all of the time.

But here is a video of me Starting EG with the python script in the tree. and the tree is empty save for 2 python scripts. and one of them is in the AutoStart folder. and you will see EG start. and the log scroll. and no movement. and then you will see me scroll the log down manually and run the script once again. and the log does not scroll.

![noscrolling](https://cloud.githubusercontent.com/assets/10932297/17766608/2dbf0dfc-64e9-11e6-9bd7-cab45e204b10.gif)


the video is an Animated gif at 640x480

**Comment by kdschlosser** [comment]
Nothing is overridden it does this same thing with the beta 2 build, as well as the code gotten directly from github and compiled with no changes made to it.

**Comment by blackwind** [comment]
Got it -- silly, non-standard wxWidgets behavior at fault. If you select the last item on the list, you'll notice that the bottom of the dotted selection border around the item is cut off. Normally in Windows forms, if an entire list item can't be shown, the list will scroll down one more notch, and because it didn't here, the scrolling code wasn't properly detecting you being at the bottom. I've changed it to scroll on the last line OR the second last line.

**Comment by kdschlosser** [comment]
ok I did mention the text being cut off.

guess that had something to do with it :-P

and why would it scroll if i closed a dialog?

and yes if i just simply stretch the window down it starts scrolling.

Cool! That has been annoying me to bits all day.

and if you take a look see at my "Overriding" code for the Scroll Lock plugin. might provide a solution. I didn't have a problem with it scrolling properly. just had that thing where it had to restart the frame to be rid of the checkbox for the autoscroll. :-O

Sorry had to poke ya a bit on that one.

**Comment by blackwind** [comment]
> ok I did mention the text being cut off.

You're right. I wasn't sure what you meant at the time, and then completely forgot about it.

> and why would it scroll if i closed a dialog?

I haven't the foggiest idea.

**Comment by kdschlosser** [comment]
well i am glad you found the problem. eventually i would have figured out that re sizing the window would fix it. and i did try that but i guess i still didn't get the size just right to make it work. it is strange that the closing of another dialog would make it go. could be some way the changing of focus on a frame caused a Layout() and that refreshed the frame. however back to this InstallModule thing. almost have pip working. big pain in the backside though.

**Comment by topic2k** [comment]
Hello @kdschlosser , i tried another way to autoscroll the loglist. Can you test [this file](https://github.com/topic2k/EventGhost/blob/ee7a4e328066129b22b10cf2dfdb049be211563f/eg/Classes/MainFrame/LogCtrl.py) if it makes any different or fixes the scrolling problem? ([my fix autoscroll branch](https://github.com/topic2k/EventGhost/tree/fix_autoscroll)

**Comment by kdschlosser** [comment]
Yeah give me a few hours tho

**Comment by kdschlosser** [comment]
it's so close to working right. but ocassionally it well not work properly. and end up a bunch of lines scrolled back in the log.

and here is an image also it's sometimes still not getting the whole line.

![log](https://cloud.githubusercontent.com/assets/10932297/18030198/2ace1b18-6c6b-11e6-9416-3a1cf1c91e72.jpg)
i am going to make a agif of it jumping backwards in the log so maybe it might help. and i know that people wouldn't do what i am going to in the agif. but this is the only way i have found to poke it with a stick if you get my meaning.

**Comment by kdschlosser** [comment]
oh an also, the above image i am scrolled all the way down and if an event is generated, it does not automatically scroll anymore

**Comment by kdschlosser** [comment]
unfortunately i am unable to make the agif,
here is what i was doing to get it to not work properly on demand.

i was grabbing the bottom left corner and going to counter clockwise rotation then the other direction. i would do that a couple of times in each direction and sometimes it will and sometimes it won't have the problem. but i had a full log each time.

and i am not usre if there is a way to set up a wxCallLater do call the layout or however you have refreshing the screen or moving the log entries. and if another resize event occurs to cancel the calllater and create a new one to do the redraw

**Comment by kdschlosser** [comment]
ok. i have got a solution. take the code in the LogCtrl.py the one have just created as a test for a solution.

this is what is happening. if you move the frame to fast on resize it gets it's self all jumbled up is what i have found.

so what i have done is this..

I have not done any code cleanup on this to remove the unused pieces but this fixes the issue. you can clean it up or leave it. but it works.

the lines of code in the __init__ i removed the binding for the EVT_LIST_CACHE_HINT and added 2 variables in it's place

`
        self.Bind(wx.EVT_KILL_FOCUS, self.OnKillFocus)
        self.Bind(wx.EVT_SIZE, self.OnSize)

        self.listBottom = None
        self.resizeTimer = None
`
then i changed the Scroll() and the OnSize() to what is below.
`
def OnSize(self, evt):
        if self.listBottom is None:
            self.listBottom = self.Scroll()
        else:
            self.Scroll(self.listBottom)
        try:
            self.resizeTimer.Stop()
        except:
            pass
        self.resizeTimer = wx.CallLater(10, setattr, self, 'listBottom', None)
        evt.Skip()

    def Scroll(self, listBottom=None):
        listTotal = self.GetItemCount()
        listTop = self.GetTopItem()
        listPP = self.GetCountPerPage()
        if listBottom is None:
            listBottom = min(listTop + listPP, listTotal - 1)
        if (listBottom - listTotal) + 1 == 0:
            self.ScrollList(0, 1000000)
        else:
            self.EnsureVisible((listBottom - 1))

        return listBottom

`

this fix has fixed the issue with the bottom line being cut off as well. and there will always be a small white space below the bottom most line.

I took this code from my "Auto Scroll Lock" plugin that I created for older versions of EG and added the resizing bits to it to handle having the page bottom always be at the bottom. Now i am not sure if i could just do a EnsureVisible on it. so i figured what the hell it really wouldn't be that hard to just run it through the Scroll() to make sure the calculations were correct

**Comment by topic2k** [comment]
Ok, again another way to handle the autoscroll. With the last approach i was able to get the occasional misbehaviour. With the new approach i wasn't able. So i might have found a proper working autoscroll.
If you don't mind @kdschlosser , then it would be great if you could test it when you have some time.
(I have [updated](https://github.com/topic2k/EventGhost/blob/a1871831b27231c356bbe2f65989895ee84bd845/eg/Classes/MainFrame/LogCtrl.py) the [branch](https://github.com/topic2k/EventGhost/tree/fix_autoscroll))

**Comment by kdschlosser** [comment]
no worries. i'll give it a go. nasty little bugger this scrolling thing

**Comment by kdschlosser** [comment]
no bueno on that one either.

here is my test setup. and what i did to induce the problem

    for i in range(50):
        eg.TriggerEvent(str(i))

simple python script.

it fills the log and give you and identifiable position.

run it then scroll back to say event Main.27

have that as the last line. then grab a corner and do a few circles changing rotation direction. When you let go it will not scroll to having the event Main.27 as the last line.

**Comment by kdschlosser** [comment]
I have a really close solution. You might be able to get it perfect. this will keep it in the right place unless you move crazy slow then it will not scroll the list. but if you move the box quickly well not really just a little bit faster than crazy slow it will scroll properly. i am not sure why but the listctrl doesn't like to move in small pixel numbers, that is a wx bug i think

    def OnSize(self, evt):
        try:
            height = self.GetItemRect(self.GetTopItem()).GetHeight()
        except:
            pass
        else:
            lastSize = self.lastSize
            newSize = self.GetSize()[1]

            size = lastSize - newSize

            if lastSize > height:
                self.ScrollList(0, size)
                self.lastSize = self.GetSize()[1]

        evt.Skip()

and just bind the EVT_SIZE

give it a try and see if it's something you might be able to fine tune

**Comment by topic2k** [comment]
Sorry to ask, but did you try my second solution? I'm not able to reproduce anymore misbehaviour with my second (current) approach. Did you use 0.5.0b3 without modifications for testing?
The only thing that one could complain about: while resizing the log won't be scrolled, only after the resizing has finished.

Your solution doesn't work for me. It won't scroll the list to the end after resizing (if the list were at the end before sizing). Hmm, do we have different versions (EG and/or wx)? I used [v0.5.0-beta3](https://github.com/EventGhost/EventGhost/tree/v0.5.0-beta3) and wxPython 3.0.2.0 classic.

**Comment by kdschlosser** [comment]
i downloaded the zip right from your fork and used that and i have the version of wx from the EventGhost dependencies download
